### ISSUE TITLE
unable to find protected tag api

### ISSUE THREAD

**Issue by ramarro123** [gitlab4j/gitlab4j-api#1000]
hi, 

this is more an help need than a feature/bug report, hope it's the right channel to do that.

i can't find this api
https://docs.gitlab.com/ee/api/protected_tags.html

more specifically i need
https://docs.gitlab.com/ee/api/protected_tags.html#protect-repository-tags

can you point me in the right direction?

**Comment by jmini** [comment]
Yes the method seems to be missing in `TagsApi`.

**Comment by DoubleDPro** [comment]
I took to work

**Comment by DoubleDPro** [comment]
@ramarro123 there is a mistake in JavaDoc for method protectTag with GitLab Endpoint: POST /projects/:id/protected_tags. I fixed it in my PR. It seems like method works correctly so you can use it. I advise you to use source code to find this method before my fix will merge.

**Comment by jmini** [comment]
Nice catch, I did only search for `POST /projects/:id/protected_tags` in the source code, so I could not find the method.
