### ISSUE TITLE
Hi plz support approve new user

### ISSUE THREAD

**Issue by laufermi** [gitlab4j/gitlab4j-api#1006]
The gitlab api as below:
https://docs.gitlab.com/ee/api/users.html#approve-user

**Comment by laufermi** [comment]
Thanks very much, guys

**Comment by jmini** [comment]
Have a look at the PR https://github.com/gitlab4j/gitlab4j-api/pull/1007, let me know if you would like to test this change in advance with jitpack.

**Comment by laufermi** [comment]
👍👍👍 Awesome !
