### ISSUE TITLE
get .gitlab-ci.yml template

### ISSUE THREAD

**Issue by ailkchenghc** [gitlab4j/gitlab4j-api#1010]
How can i get the .gitlab-ci.yml template file when i create pipline?
In this api,i can not find it.

**Comment by ailkchenghc** [comment]
this api GET /templates/gitlab_ci_ymls and CI Lint API can not find.

**Comment by jmini** [comment]
You are right this seems to be missing in this client.

Corresponding docs for the endpoint: https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html

Fell free to create a PR to add it.

**Comment by DoubleDPro** [comment]
In work!
