### ISSUE TITLE
Add the .not() operator to the MergeRequestFilter

### ISSUE THREAD

**Issue by KoCoder** [gitlab4j/gitlab4j-api#1049]
Returns merge requests that do not match the parameters supplied. Works with labels, milestone, author_id, author_username, assignee_id, assignee_username, reviewer_id, reviewer_username, my_reaction_emoji

**Comment by ritikverma2000** [comment]
Hi @KoCoder  I would like to work on this issue can you asisgn me this issue ?

**Comment by KoCoder** [comment]
Since I'm not a maintainer of this Repository, I can't assign you to this issue. Anyways feel free to implement this on your own fork and then create a PR.

**Comment by jmini** [comment]
I thought I already did it, but the open MR is adding the `not` support in the `EpicFilter`: https://github.com/gitlab4j/gitlab4j-api/pull/1005/

Usage of the `not` attribute is described here:
https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

I welcome a PR for this issue. 
@ritikverma2000 feel free to work on it.
