### ISSUE TITLE
Usage question: Ho to get groups shared with a group?

### ISSUE THREAD

**Issue by nemoo** [gitlab4j/gitlab4j-api#1053]
This is not a bug report, but a usage question.

I am sharing a group with a different group via this call:
 `gitLabApi.getGroupApi.shareGroup(groupId, shareWithGroupId, AccessLevel.REPORTER, inTenYears)`

My problem is that sometimes, the group is already shared and therefore the shareGroup command fails (correctly). 

How can I find out if the group is already shared with a different group via the API?

edit: I know that api.getGroupApi.getDescendantGroups() is not what I need.

**Comment by jmini** [comment]
Are you sure that "Descendant Groups" can be used to see with which group a group was shared? 
Documentation: https://docs.gitlab.com/ee/api/groups.html#list-a-groups-descendant-groups

Have you a way to check directly on the API (using `curl` or Postman -- I mean without gitlab4j)? 
Which call are you performing?

**Comment by nemoo** [comment]
>Are you sure that "Descendant Groups" can be used to see with which group a group was shared?

I am sure that "Descendant Groups" can **not** be used for my purpose. 

>Basically for a group called <your group>, you want what is in the tab in the UI:
>https://gitlab.com/groups//-/group_members?tab=groups
Exactly! But I want to use gitlab4j, not the UI.

I was expecting something like this:
```
    val group = gitLabApi.getGroupApi.getGroup(groupId)
    val groups = group.getSharedGroups()
```
 but getSharedGroups does not exist on the Group class.

When using the rest api and not gitlab4j, I could maybe read it from the group details: https://docs.gitlab.com/ee/api/groups.html#details-of-a-group there seems to be field on the group called "shared_with_groups".

**Comment by jmini** [comment]
The `shared_with_groups` attribute seems the way to go. I have opened https://github.com/gitlab4j/gitlab4j-api/pull/1057 to add it to the `Group` class, because it is currently missing.
