### ISSUE TITLE
API call for Branch name template

### ISSUE THREAD

**Issue by 06luki06** [gitlab4j/gitlab4j-api#1080]
Current used version: `6.0.0-rc.4`

I already had a look at the JavaDocs, but there I could only find template methods corresponding to `LicenseTemplate` and `GitLabCiTemplate`.

Is it possible to add an API call for setting the Branch name template?

Setting can be found within GitLab under `Settings` -> `Repository` -> `Branch defaults` -> `Branch name template`

![image](https://github.com/gitlab4j/gitlab4j-api/assets/95306265/6c27e78f-c199-47fd-947b-45840c641e74)

**Comment by jmini** [comment]
Do you have a pointer for this in the GitLab API doc https://docs.gitlab.com/ee/api/api_resources.html ?

I think it can be added once we have identified where it is missing.

**Comment by 06luki06** [comment]
@jmini They are within the [Projects API](https://docs.gitlab.com/ee/api/projects.html)

The corresponding attribute is:

- issue_branch_template

Would also be nice, if you could add methods for those two as well:

- merge_commit_template
- squash_commit_template
