### ISSUE TITLE
Missing feature of creating a note-webhook

### ISSUE THREAD

**Issue by 06luki06** [gitlab4j/gitlab4j-api#1121]
The ProjectAPI.addHook() method misses the functionality of adding a note-hook using this method.

I tried to create a pull request for this - but unfortunately, I do not have write-permissions for this repo.

**Comment by jmini** [comment]
PR is welcomed.

> I tried to create a pull request for this - but unfortunately, I do not have write-permissions for this repo.

You need to create your own fork of this repo.

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by 06luki06** [comment]
@jmini ah, alright - thank you! 🙂
