### ISSUE TITLE
Check if user exists endpoint

### ISSUE THREAD

**Issue by BrianSetz** [gitlab4j/gitlab4j-api#1135]
I may have overlooked it, but it looks like the endpoint `https://gitlab.com/users/:username/exists` is not implemented? 

Example: https://gitlab.com/users/example/exists

Which returns:

```json
{ "exists":true }
```

If it is indeed not available in gitlab4j, would there be an interest in adding this functionality?

**Comment by jmini** [comment]
This seems to be missing
