### ISSUE TITLE
5.6.0 includes a breaking change in the API

### ISSUE THREAD

**Issue by MarkEWaite** [gitlab4j/gitlab4j-api#1155]
I believe that the API change of the fourth argument `boolean` (primitive type, nulls not allowed) to `Boolean` (object, nulls allowed) is a breaking change in pull request:

* https://github.com/gitlab4j/gitlab4j-api/pull/1123

The change in [the diff](https://github.com/gitlab4j/gitlab4j-api/pull/1123/files#diff-9e127234e0f2bd8027b49f6e23304c0dd323640d2a9847a027ebae9d882fc7c7R2214) went from this:

```
    public ProjectHook addHook(Object projectIdOrPath, String url, ProjectHook enabledHooks,
            boolean enableSslVerification, String secretToken) throws GitLabApiException {
```

to this:

```
    public ProjectHook addHook(Object projectIdOrPath, String url, ProjectHook enabledHooks,
            Boolean enableSslVerification, String secretToken) throws GitLabApiException {
```

The Jenkins issue tracker received two reports of method not found exceptions in issue [JENKINS-73672](https://issues.jenkins.io/browse/JENKINS-73672).  

Is there a critical need for the change of type in the argument?

If not, could that change be reverted and a new release provided so that API compatibility is retained?

**Comment by basil** [comment]
Note that as of https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/438 consumers are actually depending on the _new_ signature 😬

**Comment by MarkEWaite** [comment]
Closing this issue because the Jenkins plugin has updated to the 5.6.0 API and a revert to the 5.5.0 compatible API would be another breaking change.
