### ISSUE TITLE
access token api

### ISSUE THREAD

**Issue by ramarro123** [gitlab4j/gitlab4j-api#1174]
hi,

i need to rotate a token, for security purpose (and because from gitlab 16.x the max duration is 1y)

i found some intresting api like
https://docs.gitlab.com/ee/api/user_tokens.html#create-a-personal-access-token

and

https://docs.gitlab.com/ee/api/personal_access_tokens.html#create-a-personal-access-token-administrator-only

they aren't mapped? or if they are i can't find where :(

can someone point me to the right direction? thanks!

**Comment by jmini** [comment]
With PR https://github.com/gitlab4j/gitlab4j-api/pull/1150 a new class was added `PersonalAccessTokenApi` for https://docs.gitlab.com/ee/api/personal_access_tokens.html but only the `rotate` method is implemented for now.

This can be extended if needed.

**Comment by jmini** [comment]
And for group access token there is `org.gitlab4j.api.GroupApi.rotateGroupAccessToken(Object, Long, Date)`

**Comment by jmini** [comment]
@ramarro123 I am closing this, feel free to re-open if needed
