### ISSUE TITLE
expires_at and usage_type are missing in addSshKey

### ISSUE THREAD

**Issue by otary** [gitlab4j/gitlab4j-api#1190]
![image](https://github.com/user-attachments/assets/b72924f9-709c-4d1e-9142-5a308a3cd339)
![image](https://github.com/user-attachments/assets/6d4b613e-e693-4e86-b8d2-c365779b3664)

**Comment by jmini** [comment]
Fixed with https://github.com/gitlab4j/gitlab4j-api/pull/1195
