### ISSUE TITLE
Creating a new merge request note does not allow for optional parameters

### ISSUE THREAD

**Issue by MadnessIRL** [gitlab4j/gitlab4j-api#1193]
As described in the documentation:
![image](https://github.com/user-attachments/assets/6c9e7113-88de-48b0-9c8e-18b15bb9e546)

it should be possible for example to create a note with a commit reference.
Sadly, the values:
- createdAt
- internal
- merge_request_diff_head_sha

**cannot** be set with the current note api: 

![image](https://github.com/user-attachments/assets/f0931f96-7696-4452-b63d-ebd024dde790)

This is a huge blocker for us, I attempted writing my own CURL request with no success.

**Comment by MadnessIRL** [comment]
Update: we changed the approach by utilising the getDiscussionsApi().createCommitDiscussion()

Once again, the code does not respect the contract of the documentation.
![image](https://github.com/user-attachments/assets/3aaef313-e356-4aa6-a166-f85ef307e0d2)
but the API forces position to exist and requires base, head, start Sha and positionType. 
Once those are set, the line_code will also be required, effectively preventing users to create general commit level discussions.
![image](https://github.com/user-attachments/assets/fd23fcd6-eb35-486f-b998-499d716f77cb)

With a modified null check, the comment is created successfully and the commit id stored.

**Comment by jmini** [comment]
> Once again, the code does not respect the contract of the documentation.

It is just outdated because the contract has changed. Feel free to provide a pull-request.

**Comment by MadnessIRL** [comment]
@jmini I can provide a merge request to add `createdAt` & `internal` parameters but I have no idea how to push or retrieve `merge_request_diff_head_sha`

**Comment by jmini** [comment]
The `merge_request_diff_head_sha` should be a parameter in the method used to create the note.
https://docs.gitlab.com/ee/api/notes.html#create-new-merge-request-note

> Required for the `/merge` [quick action](https://docs.gitlab.com/ee/user/project/quick_actions.html). The SHA of the head commit, which ensures the merge request wasn’t updated after the API request was sent.

I would say that when you read a merge request https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr
It corresponds to `org.gitlab4j.api.models.MergeRequest#getSha()`

But if I understand the docs, it is not required if you are not using the `/merge` quick action in your comment.

And to trigger a merge on a MR there are other API methods.

So I do not really see a use-case for this `merge_request_diff_head_sha` parameter.

What do you think?

**Comment by MadnessIRL** [comment]
I am aware that my case is quite unique and you bring up a valid point. 

With the current code, there is no way to obtain the commit sha from an existing comment.
My pull request fixes it but is it the best way?
