### ISSUE TITLE
MergeRequest API add MergeRequestFilter withReviewer by ID OR by Username

### ISSUE THREAD

**Issue by dstoianov** [gitlab4j/gitlab4j-api#1209]
Hi there, 

It would be nice to have in API method to find all MRs where user is one of the reviewers.

We already have a similar API but in this case, it is 

Examples of existing API 
```java 
MergeRequestFilter filter = new MergeRequestFilter();
filter.withoutReviewerId(123L);
//OR
filter.withoutReviewerUsername("ABC");
```

Desired API 

```java 
MergeRequestFilter filter = new MergeRequestFilter();
filter.withReviewerId(123L);
//OR
filter.withReviewerUsername("ABC");
```

if it is already implemented, please share this method or how it is possible to find all MRs assigned to user/currentUser 

Thank you
Denys

**Comment by jmini** [comment]
Can you point to GitLab REST API documentation?

I didn't look into the details, but I think a pull-request can be created to add the missing methods.

**Comment by jmini** [comment]
Indeed. Feel free to send a pull-request
