### ISSUE TITLE
Improvement: Support for Temporal replacing Date

### ISSUE THREAD

**Issue by mdeknowis** [gitlab4j/gitlab4j-api#261]
Several interfaces and structures are still using Date, even this library already depends on Java 8.

Wouldn't it be better to use `java.time.temporal.Temporal` or implementation of that instead?

**Comment by gmessner** [comment]
Moving to the new java.time data could potentially be a breaking change as GitLab is notorious for having inconsistent formatting of dates.  Much work has gone into handling these inconsistencies in a reliable way.

While I realize that there is a lot of new functionality available in java.time, I would be concerned about introducing problems with this switch.

**Comment by mdeknowis** [comment]
I see. That's a pity, as it feels wrong to use Date in Java APIs using Java 8 or later. Perhaps on the long run, it might be a quite improvement to use it in the Java API and convert it.

**Comment by gmessner** [comment]
This library has about 4000 downloads from maven central per month and has been in use for over four years, changing from date will break a lot of existing code out there. 

I am planning on cleaning out a lot of deprecated methods early next year and moving this to version 5.0.0, that will be a good opportunity to make the move to java.time.

**Comment by gmessner** [comment]
@mdeknowis 
I'm going to leave this open as a reminder that we will be making the switch to java.time with the 5.0.0 release.

**Comment by gmessner** [comment]
@mdeknowis 
I know it has been quite a while since this issue was discussed, but after much consideration and talking with several important users of this library I have decided to not make the switch, it would simply cause too much pain for existing users.
