### ISSUE TITLE
How to push some local changes

### ISSUE THREAD

**Issue by s18634879388** [gitlab4j/gitlab4j-api#342]
Which API should I use to push some  local changes？
Is there a demo?

**Comment by s18634879388** [comment]
Api can't do that

**Comment by gmessner** [comment]
@s18634879388 
You are correct in that the API cannot push local commits to the remote repo, but it can create a commit with 1 or more files via the API.  See https://docs.gitlab.com/ce/api/commits.html#create-a-commit-with-multiple-files-and-actions

I have just completed some enhancements around this with an integration test that show how to use it. I will let you know when it is released.

**Comment by s18634879388** [comment]
> @s18634879388
> You are correct in that the API cannot push local commits to the remote repo, but it can create a commit with 1 or more files via the API. See https://docs.gitlab.com/ce/api/commits.html#create-a-commit-with-multiple-files-and-actions
> 
> I have just completed some enhancements around this with an integration test that show how to use it. I will let you know when it is released.

Wow, you are awesome.

**Comment by AudiVehicle** [comment]
solved？how？how to push?
