### ISSUE TITLE
ProjectApi#getProjects always result an exception

### ISSUE THREAD

**Issue by original-codematrix** [gitlab4j/gitlab4j-api#346]
Every time I try to get all the projects per `ProjectApi` I get the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.util.ArrayList.<init>(ArrayList.java:157)
	at org.gitlab4j.api.Pager.all(Pager.java:349)
	at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:73)
```

Some Input:
I have a group with 2 other subgroups. Only the subgroups contain projects. If I try to search specific projects it works fine.

**Comment by gmessner** [comment]
@original-codematrix 
What version is your GitLab server?

**Comment by original-codematrix** [comment]
Doesn't use an own hosted GitLab I use the public one. But the `getOwnedProjects()` worked now for me. Problematic was as you said the limiting.

**Comment by gmessner** [comment]
@original-codematrix 
Definitely, the right decision to go with ```getOwnedProjects()```

I actually just released a fix for when the rate limit is hit (version 4.10.14).  I would appreciate it if you could make the call to get all projects and let me know how it behaves.

BTW, it sometimes takes an hour or two before the new release is available. so make sure you are doing this against 4.10.14

**Comment by original-codematrix** [comment]
Pre information:
```xml
<dependency>
    <groupId>org.gitlab4j</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>4.10.14</version>
</dependency>
```
@gmessner 
If now the `ProjectApi#getProjects()` method gets called it runs in an endless call/loop somewhere.
I tried it 2-3 times and every time it gets stuck.

**Comment by gmessner** [comment]
@original-codematrix 
In a debugger, I just tried going against https://gitlab.com and it is not in an endless loop, it is trying to read all the projects from the public GitLab server and there must be many hundreds of thousands of them.

It is taking about 25 seconds per 96 projects, so it will take quite a while to read them all if it does not run out of memory before all have been read. 

I believe the answer here is to clarify the documentation on the use of this method and other methods that could possibly return large numbers of results and warn against this type of use, The other option would be to add a library-wide setting to set the max number of items that can be returned and default it to 100. 

If you want to read items that may have many results, you should really use the methods that return a Pager instance.

**Comment by original-codematrix** [comment]
So far I haven't debugged it to see how long it takes avg. per 96 projects. But yes it would be better to improve the documentation on that method. While I tested it I wait at least 5 mins min. to see if it loads enough but ya.

So far my solution is `getOwnedProjects()` to clarify that for someone who maybe runs into that problem also.

**Comment by gmessner** [comment]
@original-codematrix 
Please disregard the 3 commits that were just done, they should have been against #349 instead of this issue.
