### ISSUE TITLE
support access level for project user

### ISSUE THREAD

**Issue by liangshengzh** [gitlab4j/gitlab4j-api#348]
The all member api response has access_level field, but the ProjectUser model does not have the access field. 

https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

`[
  {
    "id": 1,
    "username": "raymond_smith",
    "name": "Raymond Smith",
    "state": "active",
    "avatar_url": "https://www.gravatar.com/avatar/c2525a7f58ae3776070e44c106c48e15?s=80&d=identicon",
    "web_url": "http://192.168.1.8:3000/root",
    "expires_at": "2012-10-22T14:13:35Z",
    "access_level": 30
  },
  {
    "id": 2,
    "username": "john_doe",
    "name": "John Doe",
    "state": "active",
    "avatar_url": "https://www.gravatar.com/avatar/c2525a7f58ae3776070e44c106c48e15?s=80&d=identicon",
    "web_url": "http://192.168.1.8:3000/root",
    "expires_at": "2012-10-22T14:13:35Z",
    "access_level": 30
  },
  {
    "id": 3,
    "username": "foo_bar",
    "name": "Foo bar",
    "state": "active",
    "avatar_url": "https://www.gravatar.com/avatar/c2525a7f58ae3776070e44c106c48e15?s=80&d=identicon",
    "web_url": "http://192.168.1.8:3000/root",
    "expires_at": "2012-11-22T14:13:35Z",
    "access_level": 30
  }
]`

**Comment by gmessner** [comment]
@liangshengzh 
A ```ProjectUser``` is different than a project ```Member``` and are accessed differently:
Project Users: https://docs.gitlab.com/ee/api/projects.html#get-project-users
Project Members: https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project

To get project members you should call one of the following in ```ProjectApi```:
```
public List<Member> getMembers(Object projectIdOrPath)
public List<Member> getMembers(Object projectIdOrPath, int page, int perPage)  
public Pager<Member> getMembers(Object projectIdOrPath, int itemsPerPage) 
```
The ```Member``` class does include the ```access_level``` field.  However, ```Member``` is missing a few fields that were added in later versions of GitLab:
```
avatar_url
expires_at
web_url
```
I will update ```Member``` to add these new fields.  In the next release of this library.

**Comment by gmessner** [comment]
@liangshengzh 
Both ```ProjectApi``` and ```GroupApi``` now have ```getAllMembers()``` in the latest release (4.10.15).  The ```Member``` class has also been updated to match the latest specs from the GitLab documentation.

If you could verify it meets your needs and close this issue I would appreciate it.

**Comment by liangshengzh** [comment]
@gmessner 
yes, it's just what I need. i have upgraded to the latest release and verified.  
Thank you!  

i will close this issue
