### ISSUE TITLE
Improvement: Revert commit funcionality

### ISSUE THREAD

**Issue by arvist** [gitlab4j/gitlab4j-api#355]
Could not find revert functionality in CommitsAPI sub API
It has been recently added in GitLab API:
https://docs.gitlab.com/ee/api/commits.html#revert-a-commit

**Comment by gmessner** [comment]
@arvist 
The ```CommitsApi.revertCommit()``` method has been added and released in version 4.10.19.

If you could verify and close this issue I would appreciate it.

**Comment by arvist** [comment]
@gmessner Tested revert functionality - works great. 
Thanks, for quick turnaround
