### ISSUE TITLE
Unable to access GitLab APIs

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#363]
I need to connect with gitlab.com APIs. I am running the following code:

```Java
import org.gitlab4j.api.models.Project;

import java.util.List;

public class Foo {

    public static void main(String[] args) throws GitLabApiException {
        GitLabApi gitLabApi = new GitLabApi("https://gitlab.com/api/v4/", "xxxx");
        List<Project> projects = gitLabApi.getProjectApi().getProjects();
        projects.forEach((project ->
            System.out.println(project.getWebUrl())
        ));
```

I receive an Exception:
```Java
Exception in thread "main" org.gitlab4j.api.GitLabApiException: 404 Not Found
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:191)
	at org.gitlab4j.api.Pager.<init>(Pager.java:88)
	at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:103)
	at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:75)
	at Foo.main(Foo.java:14)
```

I have tried other hostUrl combinatoins such as `http://www.gitlab.com`, `https://www.gitlab.com`, `https://gitlab.com/api/v4`, `https://gitlab.com` etc but does work raising errors like `Permanent Redirect`, `Moved Permanently` etc. It also doesn't work with `username`, `password` login function.

@gmessner Can you tell me what is wrong?

**Comment by gmessner** [comment]
@baymac 
The correct server URL is ```https://gitlab.com```, you will get a 404 using any of the other URLs.

The call you are trying to make is trying to pull down every project at ```https://gitlab.com``` so it will take hours to return and you could possibly be rate limited because there are 100,000's or millions of them. 

This can be quickly validated by using ```gitLabApi.getProjectApi().getOwnedProjects();``` which will only pull down the projects you own.

I believe the ```login``` function is not working because you are using the wrong URL, try it with ```https://gitlab.com```

**Comment by baymac** [comment]
Okay, I get my mistake now. I was using gitlab.com as my own server, which was wrong. 

Just a quick check how do I get the owner details after connecting to the server? For example, the details of the user whose Personal Access Token is used to access the GitLab APIs.

**Comment by baymac** [comment]
I got it.

```Java
User currentUser = gitLabApi.getUserApi().getCurrentUser();
System.out.println(currentUser.getUsername());
```
Thanks for the help @gmessner.

**Comment by gmessner** [comment]
@baymac 
Here's a little snippet of code I had laying around that uses a Pager to fetch all projects from the gitlab.com server.  From my experience it takes about 25 seconds per 50 projects, so you can imagine how long it would take to read 1,000,000+ projects
```
import java.time.Instant;
import java.util.HashSet;
import java.util.Set;

import org.gitlab4j.api.GitLabApi;
import org.gitlab4j.api.Pager;
import org.gitlab4j.api.models.Project;

// This example uses a Pager to lazy stream all projects from the GitLab.com server.
// Using a lazy stream allows you to iterate over all projects one page at a time
public class FetchAllProjects {
    public static void main (String[] args) throws Exception {
        GitLabApi gitLabApi = new GitLabApi("https://gitlab.com", "YOUR_GITLAB_ACCESS_TOKEN");

        // Get the Pager for all projects, this will also fetch the first page.
        // This also configures the Pager to fetch 50 items per page
        long start = Instant.now().toEpochMilli();
        Pager<Project> pager = gitLabApi.getProjectApi().getProjects(50);

        final Set<Integer> fetchedProjectIds = new HashSet<>();
        final Set<Integer> duplicateProjectIds = new HashSet<>();
        pager.lazyStream().forEach(p -> {

            Integer projectId = p.getId();
            if (fetchedProjectIds.add(projectId)) {
                System.out.format("projectId=%d, projectName=%s, totalProjects=%d%n",
                        projectId, p.getName(), fetchedProjectIds.size());
            } else {
                duplicateProjectIds.add(projectId);
                System.out.format("%nDuplicate project ID, projectId=%d, projectName=%s, totalDuplicateProjects=%d%n%n",
                        projectId, p.getName(), duplicateProjectIds.size());
            }
        });

        long stop = Instant.now().toEpochMilli();
        System.out.format("Fetched all projects: totalItems=%d, totalDuplicateItems=%d, totalFetchTime=%f seconds%n",
                fetchedProjectIds.size(), duplicateProjectIds.size(), (stop - start) / 1000.0);
    }
}
```

**Comment by danuvian** [comment]
I also tried getting the namespace with gitlab4j first and then setting that namespace into the project. Still did not work.

var projects = gitLabApi.getProjectApi().getOwnedProjects();

        log.debug("API version = {}", gitLabApi.getApiVersion());

        var namespaces = gitLabApi.getNamespaceApi().findNamespaces("my-group");
        Namespace myGroup= null;
        for(var ns : namespaces) {
            log.debug("found namespace = {}, id = {}", ns.getName(), ns.getId());
            if(ns.getName().equals("my-group")) {
                myGroup= ns;
                log.debug("found my-group, id = {}, id2 = {}, name2 = {}", myGroup.getId(), ns.getId(), ns.getName());
                break;
            }
        }
        if(myGroup== null) {
            throw new RuntimeException("Could not find group 'my-group'");
        }
        for(var proj: projects) {
            var namespace = proj.getNamespace().getName();
            log.debug("proj: id = {}, proj with namespace = {}, namespace = {}, namespace id = {} ", proj.getId(), proj.getNameWithNamespace(), namespace, proj.getNamespace().getId());

            if("myname".equals(namespace) && "myproj".equals(proj.getName())) {
                proj.setNamespace(myGroup);
                proj.withNamespace(myGroup);
                var p = gitLabApi.getProjectApi().updateProject(proj);
                log.debug("-----------> !!! set new namespace for {} to {}, group id = {}", proj.getName(), myGroup.getName(), myGroup.getId());

            }
        }
