### ISSUE TITLE
gitLabApi.getRunnersApi().getAllRunners(scope) fails with "scope does not have a valid value"

### ISSUE THREAD

**Issue by BorisDaich** [gitlab4j/gitlab4j-api#365]
when talking to https://gitlab.com

sample code that fails 
```
                RunnerStatus scope = RunnerStatus.SHARED;
GitLabApi gitLabApi = new GitLabApi("https://gitlab.com", U.GITLAB_COM_TOKEN)
		List<Runner> allRunners2 = gitLabApi.getRunnersApi().getAllRunners(scope);
		log.debug("Shared Runners:\n{}", allRunners2);
````

throws 

org.gitlab4j.api.GitLabApiException: scope does not have a valid value
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:191)
	at org.gitlab4j.api.Pager.<init>(Pager.java:88)
	at org.gitlab4j.api.RunnersApi.getAllRunners(RunnersApi.java:244)
	at org.gitlab4j.api.RunnersApi.getAllRunners(RunnersApi.java:169)

in the pom.xml 
<dependency>
			<groupId>org.gitlab4j</groupId>
			<artifactId>gitlab4j-api</artifactId>
			<version>4.11.4</version>
		</dependency>

-----------------------------

possible reason 
JerseyWebTarget { https://gitlab.com/api/v4/runners?scope=shared&per_page=96&page=1 }
but should be 
https://gitlab.com/api/v4/runners/all?scope=shared&per_page=96&page=1 

notice the /all in the path ...

will return 

{
    "message": "403 Forbidden"
}

which is the whole different story....

**Comment by gmessner** [comment]
@BorisDaich 
You did locate the issue, I will get that corrected today and will actually be deprecating the methods that filter on ```scope``` as it's use is deprecated, see:
https://docs.gitlab.com/ee/api/runners.html#list-all-runners

As per the docs, I will be adding methods that take ```type``` and ```status``` to replace these methods. I will also create an integration test that tests these new methods in the ```RunnersApi```

**Comment by BorisDaich** [comment]
Wow that was one fast response!  I so much appreciate it! 
your API is much more usable than the "official" one! IMHO. 

so if we are at it... I am writing a comprehensive migration tool for gitlab from on premise installation to the  gitlab.com 
so as you do not have Java Wrapper for the import / export API I already wrote my own ugly code.
do you want me to try to make it to something that you can incorporate into the the lib?

**Comment by gmessner** [comment]
@BorisDaich 
Just an FYI, I am assuming that you are referring to https://github.com/timols/java-gitlab-api as the "official" one.  There actually is not an "official" one, the author of the java-gitlab-api is incorrectly using ```org.gitlab``` in his package names, and it is not part of gitlab.org, I have thought about mentioning this to one of my contacts at GitLab, as it does lead to some confusion. 

Concerning the import/export question, if you could send me the URL to the API docs I will take a look and get back to you on it.

**Comment by gmessner** [comment]
@BorisDaich 
The ```getAllRunners()``` has been fixed and new methods added that take ```type``` and ```status``` as parameters, since the ```scope``` parameter is now deprecated.

Concerning the following error:
```
{
"message": "403 Forbidden"
}
```
You will receive that calling ```getAllRunners()``` if the account being used is not an admin account. 

When you have time please verify and close this issue.

**Comment by gmessner** [comment]
@BorisDaich 
Can I close this issue since the fix has been released?

**Comment by BorisDaich** [comment]
Thanks it works as expected.

**Comment by BorisDaich** [comment]
@gmessner 
> Concerning the import/export question, if you could send me the URL to the API docs I will take a look and get back to you on it. I believe you are likely using:
> https://docs.gitlab.com/ee/api/project_import_export.html
> 

yes that one

**Comment by gmessner** [comment]
@BorisDaich 
I have completed most of the work on the import/export API, Should be doing a release this weekend with this functionality. I may not be including any integration testing because of the asynchronous nature of this.

**Comment by gmessner** [comment]
@BorisDaich 
FYI, The ImportExportApi is available in release 4.11.7.  Actually ended up including integration tests, made it a lot easier to test the implementation.

**Comment by BorisDaich** [comment]
I took a look on the code. and wow. it way cleaner than what I have did :-)
Thank you!

**Comment by creib** [comment]
Hi, I just got the same error when calling the eraseJob method.

**Comment by gmessner** [comment]
@creib 
This issue is for the ```RunnersApi```, not the ```JobApi``` so is not related to this issue. 

For the ```RunnersApi```, the 403 Forbidden error mentioned above will be returned if the user invoking the API call is not an admin account.  I would suspect that the user you are using does not have permission to erase the job.

If you have additional issues please submit a new issue.
