### ISSUE TITLE
Cannot groupApi.transferProject(groupIdOrPath, projectIdOrPath)

### ISSUE THREAD

**Issue by bdpqll** [gitlab4j/gitlab4j-api#366]
![image](https://user-images.githubusercontent.com/43171515/58874621-f482a400-86d1-11e9-82cd-53650797b2c7.png)

**Comment by gmessner** [comment]
@bdpqll 
You will get this error if you are not an admin, see:
https://docs.gitlab.com/ee/api/groups.html#transfer-project-to-group

Is the user you are using an admin?

**Comment by gmessner** [comment]
@bdpqll 
I'm going to close this as I'm pretty sure it is not an issue.  Please feel free to re-open if you need additional assistance on this.
