### ISSUE TITLE
Error on OpenJDK 11

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlab4j/gitlab4j-api#370]
Test with maven are failing on OpenJDK 11:

```
... Maven Log Before
[ERROR] testGetIssueDiscussionsByList(org.gitlab4j.api.TestIssueDiscussionsApi)  Time elapsed: 0.077 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 
Unable to initialize @Spy annotated field 'response'.

Mockito cannot mock this class: class org.gitlab4j.api.FakeResponse.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.3+7-Ubuntu-1ubuntu218.10.1
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.3+7-Ubuntu-1ubuntu218.10.1
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 4.18.0-20-generic


Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.reflect.Method#getAnnotatedReturnType
	at org.gitlab4j.api.TestIssueDiscussionsApi.setUp(TestIssueDiscussionsApi.java:34)
Caused by: org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: class org.gitlab4j.api.FakeResponse.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.3+7-Ubuntu-1ubuntu218.10.1
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.3+7-Ubuntu-1ubuntu218.10.1
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 4.18.0-20-generic


Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.reflect.Method#getAnnotatedReturnType
	at org.gitlab4j.api.TestIssueDiscussionsApi.setUp(TestIssueDiscussionsApi.java:34)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.reflect.Method#getAnnotatedReturnType
	at org.gitlab4j.api.TestIssueDiscussionsApi.setUp(TestIssueDiscussionsApi.java:34)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
	at org.gitlab4j.api.TestIssueDiscussionsApi.setUp(TestIssueDiscussionsApi.java:34)

[INFO] Running org.gitlab4j.api.TestGitLabApiBeans
[INFO] Tests run: 64, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.009 s - in org.gitlab4j.api.TestGitLabApiBeans
... Maven Log After
```

This is due to `java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter` and can be solved by adding Java EE classes to test scope for maven. See https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by gmessner** [comment]
@PhilippeVienne 
Release 4.10.0 remove all dependencies on JAXB as it was causing issues with others using this library.  What is odd is the problem with this test does not occur when using OpenJDK 12.  

Additionally, this test is really testing nothing, as it is simply mocking the call to the GitLab API, which means all it is doing is testing that the Discussion bean is working correctly.  This is already being tested by:
```
TestGitLabApiBeans.testIssueDiscussions()
```

What I would rather do is make ```TestDiscussionsApi``` an actual integration test, which would then remove the need for mocking this and thus remove the need for the JAXB dependency.  Doing the integration tests is very important as the documentation at GitLab is often wrong and changes occur in the GitLab server that breaks things.  Without the integration tests, these sort of problems would go unnoticed.

**Comment by PhilippeVienne** [comment]
I agree with other usage but is not the test scope limited to only test of the current maven project ?

Current on my local test race, the `TestDiscussionApi` was not the only one affected, I only paste this one to not have to paste the full console log.

Isn't possible to add JAXB only for testing scope ?

As OpenJDK 11 is a LTS, we should support `mvn test` on it. And it is strange that OpenJDK 12 is not affected.

I agree with you on the integration testing, may we transform all test as Integration and completely remove mocking ? That's a huge work. Can you open an Issue to have discussion on that?

**Comment by gmessner** [comment]
@PhilippeVienne 
If possible I'd like to not even have it in the test scope, it could potentially hide problems. 

All tests are not integration tests, but the tests that are testing actual API classes should be changed to integration tests, which would likely clear up this problem with Mockito.  I believe the changes would be limited to the following test classes:
```
org.gitlab4j.api.TestCommitDiscussionsApi
org.gitlab4j.api.TestEpicDiscussionsApi
org.gitlab4j.api.TestIssueDiscussionsApi
org.gitlab4j.api.TestMergeRequestApi
org.gitlab4j.api.TestMergeRequestDiscussionsApi
org.gitlab4j.api.TestSnippetDiscussionsApi
```

**Comment by PhilippeVienne** [comment]
Otherwise do you have any idea to skip those tests as I want to write additional testing but not being able to run `mvn test` is quite difficult

**Comment by gmessner** [comment]
@PhilippeVienne 
I do have some ideas, one would be to see if the ```javax.xml.bind.annotation.adapters.XmlAdapter``` class exists, and if not skip the test by using something like this:
```
assumeTrue(xmlAdapterClassExists);
```
I will look into this today and come up with a solution, what time zone are you in?

**Comment by PhilippeVienne** [comment]
@gmessner Europe/Paris UTC+2

**Comment by gmessner** [comment]
@PhilippeVienne 
I've fixed the problem with OpenJDK 11.  I simply modified FakeResponse to make it a concrete class and removed the need to use the ```@Spy``` annotation which fixed the problem. 

This is available in release 4.11.7

**Comment by PhilippeVienne** [comment]
Oh great thanks I will test it 😁

Le sam. 8 juin 2019 à 23:25, Greg Messner <notifications@github.com> a
écrit :

**Comment by PhilippeVienne** [comment]
The fix seems to work on OpenJDK. Closing the issue.
