### ISSUE TITLE
RunnerStatus.SHARED is not a valid value 

### ISSUE THREAD

**Issue by BorisDaich** [gitlab4j/gitlab4j-api#373]
When running the following code 
```
		List<Runner> allRunners2 = gitLabApi.getRunnersApi().getRunners(RunnerType.PROJECT_TYPE, RunnerStatus.SHARED);
		log.debug("Shared Runners:\n{}", allRunners2);

```
get this 
```
org.gitlab4j.api.GitLabApiException: status does not have a valid value
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:191)
	at org.gitlab4j.api.Pager.<init>(Pager.java:88)
	at org.gitlab4j.api.RunnersApi.getRunners(RunnersApi.java:125)
	at org.gitlab4j.api.RunnersApi.getRunners(RunnersApi.java:87)
	...

```

after checking the REST API docs it seems that 

RunnerStatus.SHARED is not in the list of possible values

**Comment by gmessner** [comment]
@BorisDaich 
The person that originally wrote this functionality improperly used ```RunnerStatus``` for the type of```scope``` when getting all runners (see https://docs.gitlab.com/ee/api/runners.html#list-all-runners).  So he included both ```SHARED``` and ```SPECIFIC``` as valid values for ```RunnerStatus```.  He should have created an enum for ```scope```

All the list runner methods that take ```scope``` as a parameter are now deprecated in this library and will soon be removed.  When they are removed the ```SHARED``` and ```SPECIFIC``` values will be also removed from the ```RunnerStatus``` enum.  Unfortunately for now, until the methods are removed you will need to know not to use either ```SHARED``` or ```SPECIFIC``` for a the ```status``` param when listing the runners.

**Comment by gmessner** [comment]
@BorisDaich 
I will leave this issue open until the deprecated methods have been removed and the ```SHARED``` and ```SPECIFIC``` values have been removed from ```RunnerStatus```.  

Typically I will let a month pass before removing deprecated methods and values.

**Comment by gmessner** [comment]
@BorisDaich 
I've also deprecated the SHARED and SPECIFIC enum values.

**Comment by gmessner** [comment]
@BorisDaich 
The deprecated enums and methods that used them have been removed in version 4.11.17
