### ISSUE TITLE
Impersonnation Token can have more scopes

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlab4j/gitlab4j-api#374]
Currently Impersonation Token API is limited in GitLab4J to only `api` and `read_user` but according to UI, they have as much roles as Access Token.

![image](https://user-images.githubusercontent.com/1990262/59110000-6c550680-893e-11e9-9c24-9386b04c57a5.png)

**Comment by PhilippeVienne** [comment]
I am working on a PR

**Comment by PhilippeVienne** [comment]
And yes again the GitLab documentation is not correct: https://docs.gitlab.com/ee/api/users.html#create-an-impersonation-token

**Comment by gmessner** [comment]
@PhilippeVienne 
Quite often what happens is that the UI is changed but the API documentation is not updated.  I am currently working on a PR that is all about updating the GitLab CE API documentation, I'll add this to that.

**Comment by gmessner** [comment]
@PhilippeVienne 
This has been released in 4.11.6, please verify and close when you are able.
