### ISSUE TITLE
Cannot protect branch with wildcard

### ISSUE THREAD

**Issue by bdpqll** [gitlab4j/gitlab4j-api#376]
![image](https://user-images.githubusercontent.com/43171515/59142958-79213b00-89ce-11e9-84a7-31683edbfd28.png)

**Comment by gmessner** [comment]
@bdpqll 
```RepositoryApi.protectBranch()``` does not support wildcards, you need to use ```ProtectedBranchesApi..protectBranch()``` if you want to use a wildcard.

**Comment by bdpqll** [comment]
Thanks a lot!
