### ISSUE TITLE
Can I create project within group or subgroup?

### ISSUE THREAD

**Issue by bdpqll** [gitlab4j/gitlab4j-api#380]
Sorry for my inattention, but I couldn't find a method to create a project in the group, I have to create a project and then transfer it to the group via
```
getGroupApi().transferProject(groupId, projectId);
```
Thanks in advance!

**Comment by PhilippeVienne** [comment]
Hi, what if you use:

```
getProjectApi().createProject(groupId, projectName)
```

**Comment by gmessner** [comment]
@bdpqll 
I'm assuming you would like to create the project in the group with a Project instance holding the configuration for the new project, is this correct?

Coincidently, I was just adding that functionality, it will be in tonight's release.  Will let you know when it is available.

**Comment by gmessner** [comment]
@bdpqll 
Version 4.11.8 has been released which provides the ability to create a project with a namespace ID and a Project instance with the project setup:
```
ProjectApi.createProject(Integer namespaceId, Project project)
```

The ```namespaceId``` can be a group, sub-group, or user ID.  Please verify that it meets your needs and close this issue once verified.

**Comment by bdpqll** [comment]
Thank you a loot!!
