### ISSUE TITLE
Null pointer exception on export download

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlab4j/gitlab4j-api#382]
With gitlab.com the "Content-Disposition" is not given, it causes a null pointer here on line 112:
https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/ImportExportApi.java#L111-L113

**Comment by gmessner** [comment]
@PhilippeVienne 
This has been released in 4.11.8.  Please verify and close when you have the time.

Thanks again for your contribution.

**Comment by PhilippeVienne** [comment]
@gmessner 
Thanks, it works :smile:
