### ISSUE TITLE
A public endpoint to validate the server endpoint

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#384]
Hi @gmessner,

I am trying to perform a form validation of the GitLab server url field in my Jenkins plugin. Checking the URI scheme of the provided server url might not be the right way to do it. In self hosted versions, the URL can be configured by admins so there is not specific pattern to test the server url. I am wondering if there is an API method to verify that the server url hosts a valid GitLab server but does not required authentication. For example, we make a public request to the GitLab server endpoint and get a status ok meaning the server is valid or maybe returns the version of GitLab server.

**Comment by gmessner** [comment]
@baymac 
You cannot get the version without authentication, however, you can fetch the public projects without authentication.  It is as simple as:
```
// Fetch a single project using an empty string as the access token
GitLabApi gitLabApi = new GitLabApi(gitLabServerUrlToTest, "");
List<Project> projects = gitLabApi.getProjectApi().getProjects(1, 1);
```

**Comment by baymac** [comment]
Thank you, that help. :+1:

**Comment by baymac** [comment]
Hi @gmessner,

What happens when the GitLab server does not have any public projects? The `getProjects()` throws an exception or returns `null`?

**Comment by baymac** [comment]
Sorry for the confusion, I get it now. Just saw the test case you added.

**Comment by gmessner** [comment]
@baymac 
No problem. 

BTW,  If there are no public projects the call will return a List with 0 items
