### ISSUE TITLE
How to get the charts？

### ISSUE THREAD

**Issue by shxiq01** [gitlab4j/gitlab4j-api#385]
like this ⤵️⤵️⤵️⤵️

![image](https://user-images.githubusercontent.com/12861435/59409720-7917a580-8de9-11e9-8448-2b69b2868915.png)

**Comment by shxiq01** [comment]
I want get the chart of commit and language.

**Comment by gmessner** [comment]
@shxiq01 
Understand that this library only provides a Java wrapper to the GitLab API, so it can only get data that is available via the API, which does not return charts.  

To get the language statistics take a look at the following method in the ```ProjectApi``` class:
```
public Map<String, Float> getProjectLanguages(Object projectIdOrPath) 
```
There is currently no way to get commit counts by author, you can get the total commit count of a project with the following method in ```ProjectApi```::
```
public Project getProject(Object projectIdOrPath, Boolean includeStatistics)
```

**Comment by shxiq01** [comment]
> @shxiq01
> Understand that this library only provides a Java wrapper to the GitLab API, so it can only get data that is available via the API, which does not return charts.
> 
> To get the language statistics take a look at the following method in the `ProjectApi` class:
> 
> ```
> public Map<String, Float> getProjectLanguages(Object projectIdOrPath) 
> ```
> 
> There is currently no way to get commit counts by author, you can get the total commit count of a project with the following method in `ProjectApi`::
> 
> ```
> public Project getProject(Object projectIdOrPath, Boolean includeStatistics)
> ```

tks.
