### ISSUE TITLE
Cannot get namespace via findNamespaces(String query)

### ISSUE THREAD

**Issue by bdpqll** [gitlab4j/gitlab4j-api#386]
![image](https://user-images.githubusercontent.com/43171515/59430349-b3357700-8dea-11e9-8374-f04fc59f2257.png)

![image](https://user-images.githubusercontent.com/43171515/59430388-cd6f5500-8dea-11e9-93e0-557cd69d5efa.png)

**Comment by gmessner** [comment]
@bdpqll 
```"one/two"``` is not the subgroup namespace, it is the full path for the subgroup, if you query just on ``"`two"``` it will work.

**Comment by bdpqll** [comment]
Thank you
