### ISSUE TITLE
Support masked attribute for CI Variables

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlab4j/gitlab4j-api#387]
Support the `masked` attribute for CI Variables as described in https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable

Working on PR

**Comment by gmessner** [comment]
@PhilippeVienne 
This has been released in 4.11.9.  In the process of the release, I found another problem with the GitLab documentation, the ```masked``` field is never returned in the JSON from the server, so will always be null.  I have changed the integration tests accordingly.  

Please verify and close when you have time.

**Comment by gmessner** [comment]
@PhilippeVienne 
Just wondering if you could verify and close this issue?

**Comment by gmessner** [comment]
@PhilippeVienne 
Since the fix has been released I am closing this issue.  If you find any problems feel free to re-open.
