### ISSUE TITLE
Protected Tags API

### ISSUE THREAD

**Issue by csonuryilmaz** [gitlab4j/gitlab4j-api#389]
Hi, 

I can't find `/projects/:id/protected_tags` API in the project. 

Most close one seems to be `/projects/:id/protected_branches` but I'm not sure whether it works with **protected tags**. Documentation says,

> The API has been broken up into sub API classes to make it easier to consume and to separate concerns. The GitLab4J sub API classes typically have a one-to-one relationship with the API documentation at GitLab API.

so there should be a seperate **ProtectedTagsApi** which will map to :point_right: [here](https://docs.gitlab.com/ee/api/protected_tags.html).

**Comment by gmessner** [comment]
@csonuryilmaz 
You are correct ```ProtectBranchesApi``` is a separate API.  While this library's documentation does state there is **typically** a one-to-one relationship the API documentation at GitLab API, these smaller sub-APIs are usually added to a similar sub-API, so I will add this to the ```TagsApi``` class.  Should be released later today.

BTW, I will soon be adding a table in the README.md file that shows the GitLab API name/link and which class it is implemented by, hoping to have this in place in the next week or so.

Will let you know when the release is complete.

**Comment by csonuryilmaz** [comment]
@gmessner Thanks a lot for fast response. :relaxed: 

> .. I will soon be adding a table in the README.md file that shows the GitLab API name/link and which class it is implemented by ..

That's a good idea. It'll help newcomers to see the correct mapping quickly.

> .. I will add this to the TagsApi class. Should be released later today. ..

I need to list/edit/delete protected tags from Gitlab Api in a Java app. I'll wait your next release to complete implementation. :+1: 

Thanks for the effort! :clap:

**Comment by gmessner** [comment]
@csonuryilmaz 
Release 4.11.9 is now available with support for the Protected Tags API in the ```TagsApi``` class.  Please verify and close this issue when you have time.

**Comment by csonuryilmaz** [comment]
:+1: I'll try new version and give feedback as sson as possible.

**Comment by csonuryilmaz** [comment]
It works, thanks. :tada:
