### ISSUE TITLE
DiffRefs not populating for Merge Requests List

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#391]
For my GitLab Plugin for Jenkins,

I need `DiffRefs` of Merge Request. Although `DiffRefs` get populated for single `MergeRequest` call e.g. 

```java
System.out.println(gitLabApi.getMergeRequestApi().getMergeRequest(projectpath, 1));
```

But it doesn't work when called for a list of Merge Requests. The `DiffRefs` field is returned `null`
e.g.

```java
for(final MergeRequest m : gitLabApi.getMergeRequestApi().getMergeRequests("catwoman/gitlab-bs", Constants.MergeRequestState.OPENED)) {
        System.out.println(m);
        System.out.println("-----------------");
    }
```
For getting the `DiffRefs` I need to perform an extra api call inside the for loop, e.g.

```java
for(final MergeRequest m : gitLabApi.getMergeRequestApi().getMergeRequests("catwoman/gitlab-bs", Constants.MergeRequestState.OPENED)) {
        System.out.println(gitLabApi.getMergeRequestApi().getMergeRequest(project, m.getIid()));
        System.out.println("-----------------");
    }
```

Want to know if this has to do something with default GitLab API or gitlab4j?

Thanks.

**Comment by gmessner** [comment]
@baymac 
Unfortunately, the GitLab API does not return ```diff_refs``` when fetching lists of merge requests.  See
https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests
https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests
https://docs.gitlab.com/ee/api/merge_requests.html#list-group-merge-requests

It only returns ```diff_refs``` when fetching a single merge request. see:
https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr

**Comment by baymac** [comment]
I do not see any reason for that. Anyway, thanks @gmessner as always. :)

**Comment by gmessner** [comment]
@baymac 
It may be resource intensive to fetch the diff refs, you might think about submitting an issue with GitLab to ask this question.  See https://gitlab.com/gitlab-org/gitlab-ce/issues

**Comment by baymac** [comment]
Okay, I have raised a [ticket](https://gitlab.com/gitlab-org/gitlab-ce/issues/63491).
