### ISSUE TITLE
Some profile fields for users are returned null

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#392]
Some User's profile fields such as `websiteUrl`, `twitter` are returned `null` despite containing values in the GitLab Server. Tried with both authenticated and unauthenticated in both saas and self-hosted gitlab servers.

**Comment by gmessner** [comment]
@baymac 
The ```websiteUrl```, ```twitter```, and some other fields will not be populated unless you fetching the user by ID, i.e. ```UserApi.getUser(Integer id)```.  If you are getting the user by ```username```, i.e. ```UserApi.getUser(String username)``` those fields will not be populated. 

This is because ```UserApi.getUser(String username)``` uses the list users API call but searches for a single user (by username), where ```UserApi.getUser(Integer id)``` uses the get single user by ID API call.

**Comment by baymac** [comment]
Thanks for the hint. Would have been nice if GitLab API provided these info for a list of users as well. Any idea why they might have decided to skip including these info in list of users api call?

**Comment by baymac** [comment]
@gmessner 
GitLab Group API works the same way for a list of groups and a single group (with id) like the User API. I noticed a nit inconsistency in gitlab4j. In GitLab API the list of groups doesn't contain the list of projects inside each group but in GitLab4J when the using
```java
gitLabApi().getGroupApi().getGroup(groupName);
```
it also returns the projects inside the group.

So the inconsistency is the `getGroup(groupName)` and `getUser(userName)` doesn't work the same way.

**Comment by gmessner** [comment]
@baymac 
This is not an inconsistency in GitLab4J, this is how the GitLab API works.  The GitLab API allows you to make calls to the Group sub-API using either the group path or group ID in the URL, i.e.:
```/groups/:id```
Where ```:id``` is the ID or URL-encoded path of the group 

The GitLab API User sub-API does not allow you to make calls to the User sub-API using the username in the URL it only allows the ID.  So this is an inconsistency with the GitLab API not GitLab4J.

Recall that GitLab4J is simply a Java client (wrapper) for invoking the GitLab API from Java.
