### ISSUE TITLE
Add Hook doesn't create issue event

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#394]
```java
gitLabApi.getProjectApi().addHook(project, "https://example.com", true, true,true);
```
The above code should register webhook with mergeEvents, pushEvents and IssueEvents. But the issueEvents is not registered and only the other 2 events are registered.

In gitlab4j, the `addHook` method looks like this:

```java
public ProjectHook addHook(Object projectIdOrPath, String url, boolean doPushEvents,
            boolean doIssuesEvents, boolean doMergeRequestsEvents) throws GitLabApiException {
        GitLabApiForm formData = new GitLabApiForm()
                .withParam("url", url)
                .withParam("push_events", doPushEvents)
                .withParam("issues_enabled", doIssuesEvents)
                .withParam("merge_requests_events", doMergeRequestsEvents);

        Response response = post(Response.Status.CREATED, formData, "projects", getProjectIdOrPath(projectIdOrPath), "hooks");
        return (response.readEntity(ProjectHook.class));
    }
```

I think it should be `"issues_events` instead of `issues_enabled`.

Btw what is the purpose of `issues_enabled` param?

**Comment by gmessner** [comment]
@baymac 
This is one of the complaints I have with GitLab, they change stuff like this all the time.  At one point in time the param was probably ```issues_enabled``` and it has rightfully been changed to match the pattern of the other event types to ```issues_events```.

I just pushed the fix, it will be in the next release, not sure when that will be done as I will not release with this minor of a change.

Until the release is available, you can use:
```
ProjectApi.ProjectHook addHook(Object projectIdOrPath, String url, ProjectHook enabledHooks,
            boolean enableSslVerification, String secretToken)
```

**Comment by baymac** [comment]
Thanks. Btw I see that GitLab allows to setup `comment events` in the project webhook but they do not have support for it in the api. Is there any specific reason for that?

**Comment by gmessner** [comment]
@baymac 
Comment events are actually ```note_events```, and confidential comment events are ```confidential_note_events```

**Comment by baymac** [comment]
Thanks @gmessner I didn't realise that. :sweat_smile:

**Comment by gmessner** [comment]
@baymac 
GitLab4J-APY 4.11.10 has been released with the ```ProjectApi.addHook(Project, String, Boolean, Boolean, Boolean)``` fixed.
