### ISSUE TITLE
Ntlm proxy break

### ISSUE THREAD

**Issue by jflefebvre06** [gitlab4j/gitlab4j-api#395]
Hello Greg,
Gitlab4japi not seems to works behind a ntlm or Kerberos proxy

**Comment by gmessner** [comment]
@jflefebvre06 
How are you configuring gitlab4j-api to use the proxy?

The following is used to set up the proxy during integration testing and it works with Squid:
```
// Setup a GitLabApi instance to use a proxy
Map<String, Object> clientConfig = ProxyClientConfig.createProxyClientConfig("PROXY_URI", "PROXY_USERNAME", "PROXY_PASSWORD");
GitLabApi gitLabApi = new GitLabApi(GITLAB_HOST_URL, "YOUR_PRIVATE_TOKEN", null, clientConfig);
```

**Comment by jflefebvre06** [comment]
I do the same. Are you sure squid provided a NTLM proxy ?

**Comment by gmessner** [comment]
@jflefebvre06 
NTLM is not a standard proxy protocol, so ```ProxyClientConfig.createProxyClientConfig(String, String, String)``` will not work.

I believe I have a solution for this that creates the proper clientConfig for an NTLM proxy.  Will let you know once I test it.

**Comment by gmessner** [comment]
@jflefebvre06 
GitLab4J-API 4.11.10 is available with support for NTLM proxies.  I was not able to test this (no NTLM proxy avaiable to me), so if you could verify/test I would appreciate it.

The code would look like this:
```
// Log in to the GitLab server using a Windows NTLM proxy server
Map<String, Object> proxyConfig = ProxyClientConfig.createNtlmProxyClientConfig(
        "http://your-proxy-server", "proxy-username", "proxy-password", "your-workstation", "your-domain");
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.com", "YOUR_PRIVATE_TOKEN", null, proxyConfig);
```
The ```"your-workstation"``` parameter can be null.

**Comment by jflefebvre06** [comment]
No ntlm proxy to test :(
I am looking the 2 solutions belowed to simulate 

http://www.mock-server.com/

https://github.com/shopify/toxiproxy

**Comment by gmessner** [comment]
@jflefebvre06 
Because of the nature of this library, the integration tests should be tested against actual resources, so to test the NTLM proxy functionality an actual NTLM proxy should be utilized.   The two links are designed to do something other than simulating an NTLM proxy.

I was hoping you could utilize GitLab4J-API v4.11.10 and verify that it works in a Windows network that is using Kerberos/NTLM.

**Comment by gmessner** [comment]
@jflefebvre06 
Just wondering if you have been able to verify the fix?

**Comment by gmessner** [comment]
@jflefebvre06 
Since I'm certain this issue has been fixed I am closing it.  If you find a problem with the fix please re-open the issue.
