### ISSUE TITLE
Can I query a List<Project> against a list of projectIds?

### ISSUE THREAD

**Issue by shxiq01** [gitlab4j/gitlab4j-api#397]
I want a Method like this:

`public List<Project> getMemberProjects(List<Object> projectIds, int page, int perPage)`

**Comment by gmessner** [comment]
@shxiq01 
The GitLab API does not have a way to get a list of projects given a list of project IDs.  You would need to implement this at the application level.  That would look something like this:
```
List<Project> projects = new ArrayList<>(projectIds.size());
for (Integer projectId : projectIds) {
    Optional<Project> project = gitLabApi.getProjectApi().getOptionalProject(id);
    if (project.isPresent())
        projects.add(project.get());
}

**Comment by shxiq01** [comment]
I got it, tks.
