### ISSUE TITLE
WebHook Example?

### ISSUE THREAD

**Issue by WestFarmer** [gitlab4j/gitlab4j-api#398]
Docs have no example about how to start a WebHook receiver, how to config http port for example?

**Comment by gmessner** [comment]
@WestFarmer 
The receiver would be created at the application level, Could be in a SpringBoot ```@RestController```, a Java Servlet, or any type of thing that serves ass an HTTP server.

Your application should create an instance of ```org.gitlab4j.api.webhook.WebHookManager``` and when the receiver receives the ```HttpServletRequest``` it passes it to ```WebHookManager.handleRequest(HttpServletRequest)``` on the created WebHookManager instance.  

You will want to implement the ```org.gitlab4j.api.webhook.WebHookListener``` interface with the actuall business logic and add it to your created ```org.gitlab4j.api.webhook.WebHookManager``` instance with ```WebHookManager.addListener(WebHookListener)```

I have been thinking about adding actual source code examples.  I do not have any time right now to do so, but maybe in the next couple weeks.

**Comment by WestFarmer** [comment]
I have write a example that setting up web hook receiver and system hook receiver in spring-boot jersey endpoints:
`
@Service
@Path('/gitlab/hook/web')
public class GitLabWebHookReceiver{
    @Autowired
    private WebHookManager manager ;
    @POST
    public void handle(@Context HttpServletRequest request){
          manager .handle(request);
    }
}
`

**Comment by aviorn36** [comment]
Hi @WestFarmer, @gmessner and all, by any chance are there any example which I can refer too. Would really help me with my project.
