### ISSUE TITLE
SystemHookManager expect X-GitLab-Event always equals "System Hook"

### ISSUE THREAD

**Issue by WestFarmer** [gitlab4j/gitlab4j-api#399]
I am using GitLab CE 11.4, the actual X-GitLab-Event=Push Hook, when testing with push events.

**Comment by gmessner** [comment]
@WestFarmer 
System Hooks are different than Webhooks, and are configured in different places.  System Hooks are configured for the whole server on the "Admin Area -> System Hooks" page or by using the ```SystemHooksApi```.  Webhooks are configured on the "Project -> Settings -> Integrations" page or by using the ```ProjectApi```.

If ```X-GitLab-Event``` equals ```Push Hook```, then you are looking at a Webhook not a System Hook and should be using ```org.gitlab4j.api.webhooks.WebHookManager``` not ```org.gitlab4j.api.systemhooks.SystemHookManager```

**Comment by WestFarmer** [comment]
I am pretty sure that I used "Admin Area -> System Hooks -> Test -> Push Events" , it seems there is something wrong with gitlab's system hook test functionality. Tested with real project push, all is good.

**Comment by gmessner** [comment]
@WestFarmer 
I just verified the same behavior with my GitLab server, the test functionality is actually sending the wrong ```X-GitLab-Event``` for all event types.  If you have time, maybe you could submit a bug to GitLab.
