### ISSUE TITLE
Typo in Pipeline Api

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#406]
One of the Pipeline Api method has a typo - 

See https://github.com/gitlab4j/gitlab4j-api/blob/c7e65c3e8e3755a784d4fcf0955a7efc341d86f4/src/main/java/org/gitlab4j/api/PipelineApi.java#L587

There is an extra `s`. I am not sure if it is there to maintain binary compatibility.

**Comment by gmessner** [comment]
@baymac 
This was a typo and has just been fixed.  The change will be included in the next release happening on Friday.  Will let you know when it is released.

**Comment by baymac** [comment]
Thanks.

**Comment by gmessner** [comment]
@baymac 
Release 4.11.16 is now available,
