### ISSUE TITLE
Incorrect pipeline creation failure message

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#407]
I am trying to create a pipeline using only `project path` and `hash` with :

```java
gitLabApi.getPipelineApi().createPipeline(<project_path>, <hash>);
```
GitLab4J returns: `The following fields have validation errors: base`. 

Using the curl command:

```bash
curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/1/pipeline?ref=master"
```

It returns: `{"message":{"base":["Missing .gitlab-ci.yml file"]}}`.

**Comment by gmessner** [comment]
@baymac 
The message is not incorrect, it is a validation error.  If you want to see the details of the validation error(s) you can get them with e.getValidationErrors().  Here is an example of what validation errors will hold:
```
{base=[Missing .gitlab-ci.yml file]}
```

**Comment by baymac** [comment]
Oh! That's cool. Thanks. 😅
