### ISSUE TITLE
Typo in AbstractEvent

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#413]
https://github.com/gitlab4j/gitlab4j-api/blob/ab866090262814753e68721968ba9516d238e6b4/src/main/java/org/gitlab4j/api/webhook/AbstractEvent.java#L8

Hi @gmessner, there's a typo here with an extra `s`.

**Comment by gmessner** [comment]
@baymac Thanks for the fix.  Since the PR is merged I'm going to close this issue since there is nothing to validate.

**Comment by gmessner** [comment]
@baymac FYI, 4.11.19 has been released with this in it
