### ISSUE TITLE
TagsApi search

### ISSUE THREAD

**Issue by campa** [gitlab4j/gitlab4j-api#417]
Hi, I'm using your really useful and stable lib.

I need to call GitLab TagsApi using the search param with a criteria for search , see [ here ](https://docs.gitlab.com/ce/api/tags.html) for the param use  , but I'm not able to find ( o understand how to use them ) a java method in TagsApi.

Could you suggest me the way ? or I need to create myself a lower level REST call ?

Thank you in advance.

**Comment by gmessner** [comment]
@campa 4.11.19 has been released with search capability, see the following methods in ```TagsApi```:
```
List<Tag> getTags(Object projectIdOrPath, TagOrderBy orderBy, SortOrder sortOrder, String search)
List<Tag> getTags(Object projectIdOrPath, TagOrderBy orderBy, SortOrder sortOrder, String search, int page, int perPage)
Pager<Tag> getTags(Object projectIdOrPath, TagOrderBy orderBy, SortOrder sortOrder, String search, int itemsPerPage)
Stream<Tag> getTagsStream(Object projectIdOrPath, TagOrderBy orderBy, SortOrder sortOrder, String search)
```

Please verify and close this issue when you have the time.

**Comment by campa** [comment]
I did not see under "release" list 4.11.19 , I'm using 4.11.18 .
I'll switch to 19 thank you.
