### ISSUE TITLE
Howto to use with Log4J 2

### ISSUE THREAD

**Issue by campa** [gitlab4j/gitlab4j-api#418]
There is a way for having your custom logging system working and be able to configure from log4j 2 ? I mean changing the log4j,xml for example.

thx.

**Comment by gmessner** [comment]
@campa 
I believe all you need to do is use the Log4j JDK Logging Adapter, see the following link for more info:
https://logging.apache.org/log4j/2.0/log4j-jul/index.html

If this works let me know and I'll add it to the README.md file.

**Comment by campa** [comment]
@gmessner 

I'm already using this adpater, but in order to see req-resp logging messages I need to create a util logger and pass it as here:

`
Logger org.apache.logging.log4j.LoggerGITLAB4l_LOG = LogManager.getLogger(GitLabApi.class.getPackageName());

`
....
`
java.util.logging.Logger utilLogger = java.util.logging.Logger.getLogger(GITLAB4l_LOG.getName());
gitLabApi.enableRequestResponseLogging(utilLogger, (new DefaultLevelConverter()).toJavaLevel(LOG.getLevel()));
`
I 'd like to enable and configure loggers that are internal you api , in order to debug and dignostic issues.  There is a way ? How do you configure yours ?

Thanks in advance.

**Comment by gmessner** [comment]
@campa 
In order to enable the logging of the request and responses all you need to do is call a method that sets the ```maxEntitySize```, your code would look something like this:
```
org.apache.logging.log4j.Logger GITLAB4J_LOG =
       LogManager.getLogger(GitLabApi.class.getPackageName());

...

int maxEntitySIze = 4096;
java.util.logging.Logger utilLogger = java.util.logging.Logger utilLogger =
        java.util.logging.Logger.getLogger(GITLAB4l_LOG.getName());
gitLabApi.enableRequestResponseLogging(utilLogger,
        new DefaultLevelConverter().toJavaLevel(GITLAB4J_LOG.getLevel()), maxEntitySize);
```

**Comment by campa** [comment]
Yes this is already working. I'm also asking:

I 'd like to enable and configure loggers that are internal you api , in order to debug and diagnostic issues and behaviors. There is a way ? How do I can configure yours logger levels ?

Thx

**Comment by gmessner** [comment]
@campa
The code I gave you is what enables the logger and sets the level, so I am not sure what you are asking.  The important thing is to make sure you set the maxEntitySize > 0 if you want requests and responses logged.

**Comment by campa** [comment]
Sorry @gmessner  its' mu fault, I was not able to well explain ... and also I just understood how it works. I just see in you project you are using util logger so using the adpater above can solve my needs.... it a matter of integration between logger systems not a thing of you project. Sorry.

In order to clarify, for others in future: my need was to to obtain logs message not only  for req-response, but for other parts...  for example i'd like to control also logger as this:
`public class GitLabApi {
    private final static Logger LOGGER = Logger.getLogger(GitLabApi.class.getName());`

Thank you for you patience. I'll find a solution.

**Comment by gmessner** [comment]
@campa 
This library does not really log much of anything, so without enabling the request and response logging you will see little if anything logged.

Also, when enabling the request and response logging you do not need to pass in a Logger instance, if you want to change anything with the GitLabAPi logger you can gain access to it.  Here is how that is done:
```
// Set the log level, you can also use DefaultLevelConverter().toJavaLevel()
java.util.logging.Level level = java.util.logging.Level.FINE;
int maxEntitySIze = 4096;
gitLabApi.enableRequestResponseLogging(level, maxEntitySize);

// Fetch the GitLabAPi Logger instance
java.util.logging.Logger gitlab4jLogger = GitLabApi.getLogger();
```

**Comment by dolonnen** [comment]
Hi, sorry for revitalize this old thread but maybe we can solve my problem with the logging:

- I've set the log4j LogManager as logging manager with this VM option as described [here](https://logging.apache.org/log4j/log4j-2.2/log4j-jul/index.html):
`-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager`

- In my code enable the logging in gitlab4j with this in a Constructor
`this.gitLabApi = new GitLabApi("https://" + gitlabHost, apiToken);
int maxEntitySize = 4096;
java.util.logging.Logger gitlab4jLogger = java.util.logging.Logger.getLogger(GitLabApi.class.getPackageName());
gitLabApi.enableRequestResponseLogging(gitlab4jLogger, Level.ALL, maxEntitySize);`

But I have no logging from the libary when using the _gitLabApi_.

Are there any suggestions.
