### ISSUE TITLE
How to grab related issues

### ISSUE THREAD

**Issue by royalrights** [gitlab4j/gitlab4j-api#419]
Is there any way to grab [related issues](https://docs.gitlab.com/ee/api/issue_links.html) with GitLab4J?

**Comment by gmessner** [comment]
@royalrights 
There is not currently, but I just finished the implementation.  Will be released in the next day or so.  Will let you know when it is available.

**Comment by gmessner** [comment]
@royalrights 
This functionality is available in the ```IssuesApi```, please verify and close when you have time.

FYI, This functionality is only available with GitLab Starter, Bronze, and higher tiers, if you are using GitLab-CE it will not work.

**Comment by royalrights** [comment]
@gmessner 
Seems to work like a charm.

Thanks a lot Greg, verified and closing.
