### ISSUE TITLE
create group always show 403 Forbidden

### ISSUE THREAD

**Issue by wukaiying** [gitlab4j/gitlab4j-api#421]
`GitLabApi gitLabApi = GitLabApi.login(gitlabUrl, "root", "password");

        Optional<Group> optionalGroup = gitLabApi.getGroupApi().getOptionalGroup(orgName)
        if(!optionalGroup.isPresent()){
            List<Group> groupList = gitLabApi.getGroupApi().getGroups()
            println(groupList)
            Group groupSpec = new Group()
                    .withName("alcmt")
                    .withPath("alcmt")
                    .withDescription("this is a default git repository")
                    .withVisibility(Visibility.PUBLIC)
                    .withlfsEnabled(true)
            Group newGroup = gitLabApi.getGroupApi().addGroup(groupSpec)
            println(newGroup)`

username and password is root. however,i can create the project.
by the way, how can i create a project inside the group?
Thanks!

**Comment by wukaiying** [comment]
resolved.
need setting create group permission for root in gitlab.

**Comment by gmessner** [comment]
@wukaiying 
FYI, While it is not causing you issue, the method you are using to log in is deprecated and will be removed in the next release of this library.  You should use the following method instead:
```
GitLabApi gitLabApi = GitLabApi.oauth2Login(gitlabUrl, "root", "password");
```
