### ISSUE TITLE
how to clone or download the project?

### ISSUE THREAD

**Issue by wukaiying** [gitlab4j/gitlab4j-api#423]
i need search the files with some keywords, so i want to download the project, how can i do?

**Comment by szisiu** [comment]
you can fork, clone or download a repo as a zip depending of your needs. refer to:
- https://help.github.com/en/articles/fork-a-repo
- https://help.github.com/en/articles/cloning-a-repository

**Comment by gmessner** [comment]
@wukaiying 
As @szisiu has shown there are web pages that show how to do this.  

If you are trying to use this library to download or clone a project, that is not a functionality provided by the GitLab API which this project is just a Java wrapper for, so it cannot be done.

**Comment by gmessner** [comment]
@wukaiying 
Since I have not heard any response I am closing this issue, feel free to re-open if you still need assistance.
