### ISSUE TITLE
Add projects and issues statistics api support

### ISSUE THREAD

**Issue by szisiu** [gitlab4j/gitlab4j-api#424]
Is there any chance to implement [project_statistics](https://docs.gitlab.com/ce/api/project_statistics.html) and/or [issues_statistics](https://docs.gitlab.com/ce/api/issues_statistics.html)?

**Comment by gmessner** [comment]
@szisiu These have been added in release 4.12.2.  You'll find methods in the ProjectApi and IssuesApi for fetching the statistics:
```
Project Api:
public ProjectFetches getProjectStatistics(Object projectIdOrPath)

IssuesApi:
public IssuesStatistics getIssuesStatistics(IssuesStatisticsFilter filter)
public IssuesStatistics getGroupIssuesStatistics(Object groupIdOrPath, IssuesStatisticsFilter filter)
public IssuesStatistics geProjectIssuesStatistics(Object projectIdOrPath, IssuesStatisticsFilter filter)
```

Please verify and close when you have the time.

**Comment by gmessner** [comment]
@szisiu SInce this has been released I am closing this issue.  Feel free to re-open if you run into any problems.

**Comment by szisiu** [comment]
ok. thanks @gmessner!
