### ISSUE TITLE
Does it support search api?

### ISSUE THREAD

**Issue by magaofei** [gitlab4j/gitlab4j-api#425]
https://gitlab.com/help/api/search.md

`curl --request GET --header "PRIVATE-TOKEN: <your_access_token>" https://gitlab.example.com/api/v4/projects/6/search?scope=blobs&search=installation`

I did not find the relevant code, is it supported?

**Comment by gmessner** [comment]
@magaofei 
Will add this functionality in the next release and let you know when it is available.  Should only be a day or two.

**Comment by gmessner** [comment]
@magaofei The ```SearchApi``` has been added and the code merged.  A release will be done on 9/16/2019.

**Comment by gmessner** [comment]
@magaofei  Release 4.12.3 with this functionality has been released, please verify and close this issue when you have a chance.

BTW, I did not have time to create enough tests for this, will do so when I have time.

**Comment by gmessner** [comment]
@magaofei 
I have added tests for this and fixed a bug that the tests exposed.  4.12.4 is now available.
