### ISSUE TITLE
System hook of repository update type unsupported

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#426]
I am trying to setup a system hook in gitlab server but gitlab4j doesn't seem to support the `repository update event` type. It returns the following error:
```
Aug 20, 2019 9:55:02 PM org.gitlab4j.api.webhook.WebHookManager handleRequest
INFO: handleEvent: X-Gitlab-Event=Repository Update Hook
Aug 20, 2019 9:55:02 PM org.gitlab4j.api.webhook.WebHookManager handleRequest
WARNING: Unsupported X-Gitlab-Event, event Name=Repository Update Hook
```

**Comment by baymac** [comment]
@gmessner I think I am mistaken with this bug. I will reopen if I change my mind. Sorry for the inconvenience.

**Comment by baymac** [comment]
Previously I was sending system hook events to WebhookManager so it said unsupported event. Now I am sending the system hook events to SystemhookManager it still says unsupported event.

**Comment by baymac** [comment]
My implementation can be found here - https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/30/files.

**Comment by baymac** [comment]
One of the discrepancies I have noticed is that all the system hook events should have a header `System Hook` based on [docs](https://docs.gitlab.com/ee/system_hooks/system_hooks.html#hooks-request-example) but system hook headers received are like `Repository Update Hook`, `Tag Push Hook` etc.

**Comment by baymac** [comment]
Please see https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/30#issuecomment-523159390

**Comment by gmessner** [comment]
@baymac I believe you have discovered that for a System Hook the header will always be: ```X-Gitlab-Event: System Hook```, can we close this issue?

**Comment by baymac** [comment]
Yes, my bad. :sweat_smile:
