### ISSUE TITLE
Add method to get user by external UID

### ISSUE THREAD

**Issue by Tranqyll** [gitlab4j/gitlab4j-api#427]
Add a method to get a user by its external uid/provider.

This is supported by the gitlab REST API, using:

```
GET /users?extern_uid=:extern_uid&provider=:provider
```

I'm working on a PR

**Comment by gmessner** [comment]
@Tranqyll 
This has been merged and a few changes made to fix a few things.  By default, it will not be tested, you'll need to add a ~/test-gitlab4j.properties with the settings in it, the ones in src/test/resources are commented out.

Please verify and close this issue when you have the time.

And thank you for your contribution.

**Comment by gmessner** [comment]
@Tranqyll Since this has been released I am closing this issue.  Feel free to open it back up if you find any problems.
