### ISSUE TITLE
Pulling participants from issues.

### ISSUE THREAD

**Issue by royalrights** [gitlab4j/gitlab4j-api#429]
There's functionality for getting participants from merge requests currently, but I don't see the same for issues. Is there a way to grab them from issues currently?

Link to what I want to grab [here](https://docs.gitlab.com/ee/api/issues.html#participants-on-issues).

**Comment by gmessner** [comment]
@royalrights 
Presently not available.  WIll be in the next release which will happen in the next day or two.  Will let you know when it is released.

**Comment by gmessner** [comment]
@royalrights 
This enhancement has been released in 4.12.2, please verify and close when you have time.

**Comment by royalrights** [comment]
Thanks a lot Greg, seems to work perfect.

Verified. 😃
