### ISSUE TITLE
Feature Request: Add method to query pipeline variables

### ISSUE THREAD

**Issue by marcojahn** [gitlab4j/gitlab4j-api#431]
Please add the possibility to query pipeline variables as available by the [Rest API](https://docs.gitlab.com/ee/api/pipelines.html#get-variables-of-a-pipeline)

```
curl --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/1/pipelines/46/variables"
```

with an example response of

```
[
  {
    "key": "RUN_NIGHTLY_BUILD",
    "variable_type": "env_var",
    "value": "true"
  },
  {
    "key": "foo",
    "value": "bar"
  }
]
```

API could look like the following

```java
public List<Variable> getPipelineVariables(Object projectIdOrPath, int pipelineId) throws GitLabApiException {
```

**Comment by gmessner** [comment]
@marcojahn  Release 4.12.3 with this functionality has been released, please verify and close this issue when you have a chance.

**Comment by gmessner** [comment]
@marcojahn 
I'm going to close this issue since it has been released.  If you find any problems with it please re-open this issue.
