### ISSUE TITLE
How to remove a milestone?

### ISSUE THREAD

**Issue by pvilaca** [gitlab4j/gitlab4j-api#432]
Is it possible remove a milestone?

**Comment by gmessner** [comment]
@pvilaca 
The ```deleteMilestone()``` method has been added to the ```MilestonesApi```.  This will be released on Monday 9/16/2019.

**Comment by gmessner** [comment]
@pvilaca Release 4.12.3 with this functionality has been released, please verify and close this issue when you have a chance.

**Comment by gmessner** [comment]
@pvilaca 
I'm going to close this issue since it has been released.  If you find any problems with it please re-open this issue.
