### ISSUE TITLE
Add possibility to trigger housekeeping

### ISSUE THREAD

**Issue by Schoaf** [gitlab4j/gitlab4j-api#433]
I figured that there is no way to trigger housekeeping yet although it is supported by the GitLab API:
https://docs.gitlab.com/ee/api/projects.html#start-the-housekeeping-task-for-a-project

**Comment by gmessner** [comment]
@Schoaf 
Release 4.12.4 is now available with this as part of it, please verify and close this issue when you have the time.

**Comment by gmessner** [comment]
@Schoaf I'm going to close this issue since it has been released.  If you find any problems with it please re-open this issue.

**Comment by Schoaf** [comment]
Excellent. Thanks!
