### ISSUE TITLE
Add empty_repo property to Project

### ISSUE THREAD

**Issue by SamerAdra** [gitlab4j/gitlab4j-api#435]
The projects API provides a boolean field "empty_repo" but Gitlab4j is not including this in the Project model. Could you add it please?

Reason I need it is I used the branches API to get a project's branches, but in case it has empty_repo, it throws a 500 error, so would definitely like to prevent by checking the empty_repo property.

**Comment by gmessner** [comment]
@SamerAdra 
I am not seeing that in the documentation (https://docs.gitlab.com/ce/api/projects.html), though I do see it in the actual results.  I really do not like adding things that are not officially documented.

If you submit an issue with GitLab about the documentation missing the ```empty_repo``` field and reference the issue # here I will add it.

**Comment by gmessner** [comment]
@SamerAdra 
I was going to submit a bug for GitLab throwing a 500 error when getting branches when the project is empty (empty_repo=true), but in testing, I do not get a 500 error with this, GitLab 12.1 is returning an empty array:
```
[]
```
Two questions:
1) What GitLab4J-API method is being called.
2) What version of GitLab are you using?

**Comment by SamerAdra** [comment]
I have filed the following issue requesting GitLab to add empty_repo to their documentation:
[GitLab Issue 32694](https://gitlab.com/gitlab-org/gitlab/issues/32694)

1. I am calling repositoryApi.getBranches(projectId) when I get the 500 error.
2. 12.2.4-ee

I think the error is related to the fact that the project was created from a fork, but the fork attempt failed. Can see that in the getproject result from the web API:

`{"id":123,"description":"","name":"myproject","name_with_namespace":"mygroup / myproject","path":"myproject","path_with_namespace":"mygroup/myproject","created_at":"2019-08-01T18:41:31.254Z","default_branch":null,"tag_list":[],"ssh_url_to_repo":"git@my-gitlab-url:mygroup/myproject.git","http_url_to_repo":"https://my-gitlab-url/mygroup/myproject.git","web_url":"https://my-gitlab-url/mygroup/myproject","readme_url":null,"avatar_url":null,"star_count":0,"forks_count":0,"last_activity_at":"2019-08-01T18:41:31.254Z","namespace":{"id":456,"name":"mygroup","path":"mygroup","kind":"group","full_path":"mygroup","parent_id":null,"avatar_url":null,"web_url":"https://my-gitlab-url/groups/mygroup"},"_links":{"self":"https://my-gitlab-url/api/v4/projects/123","issues":"https://my-gitlab-url/api/v4/projects/123/issues","merge_requests":"https://my-gitlab-url/api/v4/projects/123/merge_requests","repo_branches":"https://my-gitlab-url/api/v4/projects/123/repository/branches","labels":"https://my-gitlab-url/api/v4/projects/123/labels","events":"https://my-gitlab-url/api/v4/projects/123/events","members":"https://my-gitlab-url/api/v4/projects/123/members"},"empty_repo":true,"archived":false,"visibility":"private","resolve_outdated_diff_discussions":false,"container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"issues_access_level":"enabled","repository_access_level":"private","merge_requests_access_level":"private","wiki_access_level":"enabled","builds_access_level":"private","snippets_access_level":"enabled","shared_runners_enabled":true,"lfs_enabled":false,"creator_id":99,"forked_from_project":{"id":987,"description":"","name":"myproject","name_with_namespace":"Last, First / myproject","path":"myproject","path_with_namespace":"myUserId/myproject","created_at":"2019-01-15T18:34:11.862Z","tag_list":[],"ssh_url_to_repo":"git@my-gitlab-url:myUserId/myproject.git","http_url_to_repo":"https://my-gitlab-url/myUserId/myproject.git","web_url":"https://my-gitlab-url/myUserId/myproject","readme_url":"https://my-gitlab-url/myUserId/myproject/blob/master/README.md","avatar_url":null,"star_count":0,"forks_count":1,"last_activity_at":"2019-08-06T18:24:29.092Z","namespace":{"id":567,"name":"Last, First","path":"myUserId","kind":"user","full_path":"myUserId","parent_id":null,"avatar_url":null,"web_url":"https://my-gitlab-url/myUserId"}},"import_status":"failed","import_error":"Every fork attempt has failed: **Unable to fork project 123 for repository myUserId/myproject -\u003e mygroup/myproject.** Please try again.","open_issues_count":0,"runners_token":"MY_TOKEN","ci_default_git_depth":null,"public_jobs":true,"build_git_strategy":"fetch","build_timeout":3600,"auto_cancel_pending_pipelines":"enabled","build_coverage_regex":null,"ci_config_path":null,"shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"request_access_enabled":false,"only_allow_merge_if_all_discussions_are_resolved":false,"printing_merge_request_link_enabled":true,"merge_method":"merge","auto_devops_enabled":true,"auto_devops_deploy_strategy":"continuous","permissions":{"project_access":null,"group_access":{"access_level":40,"notification_level":3}},"approvals_before_merge":0,"mirror":false}`

**Comment by gmessner** [comment]
@SamerAdra 
Thanks for submitting the issue with GitLab, I will add the field later today. Will let you know when that has been added.

However, the 500 error is likely not because the repo is empty, it is because the repo is in an invalid state, I would assume that many API other calls would fail with this repo.

This is just a guess, but I believe the fork issue may be because of an invalid character in the name of the repo you are forking from: ```myUserId/myproject -\u003e mygroup/myproject```

**Comment by gmessner** [comment]
@SamerAdra Just released 4.12.5 with empty_repo property added to the ```Project``` class.  Please close and verify when you have a chance.

**Comment by SamerAdra** [comment]
Works as expected, thanks!!
