### ISSUE TITLE
GitLabApiException(Response response)  construct will devour exceptions

### ISSUE THREAD

**Issue by 490145502** [gitlab4j/gitlab4j-api#436]
![image](https://user-images.githubusercontent.com/24557435/65573503-9853d080-df9d-11e9-88bb-deba1f1868fc.png)

The implementation of jsonMessage is ContainerNode

![image](https://user-images.githubusercontent.com/24557435/65573691-0b5d4700-df9e-11e9-8305-0420ef87befd.png)

**Comment by gmessner** [comment]
@490145502 
According to the GitLab API documentation at https://docs.gitlab.com/ce/api/#data-validation-and-error-reporting if the Response is an error it will contain JSON with either ```"message"``` or ```"error"``` as the top-level field and if ```"message"``` the node will either be an object (which will is a ContainerNode) or a string value.  

Have you actually see it fall down into ```this.message = jsonMessage.asText();``` where it was not a string value?  If so could you please provide the content of the response so I can understand how it reached that point.

**Comment by 490145502** [comment]
> @490145502
> According to the GitLab API documentation at https://docs.gitlab.com/ce/api/#data-validation-and-error-reporting if the Response is an error it will contain JSON with either `"message"` or `"error"` as the top-level field and if `"message"` the node will either be an object (which is a ContainerNode) or a string value.
> 
> Have you actually see it fall down into `this.message = jsonMessage.asText();` where it was not a string value? If so could you please provide the content of the response so I can understand how it reached that point.

![image](https://user-images.githubusercontent.com/24557435/65576810-39925500-dfa5-11e9-831b-e25bacd95b07.png)

This is the response I got by calling MergeRequestApi#createMergeRequest. The "message" is indeed an array field.

**Comment by gmessner** [comment]
@490145502 
This is then a bug with the create merge request API endpoint, as according to the GitLab API docs "message" will not be an array.  We will add the handling of this condition and submit a bug with GitLab concerning the format of the error response for create merge request.

**Comment by gmessner** [comment]
@490145502 
GitLab4J-API release 4.12.6 has been released that properly handles a response when "message" is an array.

Please verify and close this issue when you have a chance.

**Comment by jasenye** [comment]
> @490145502
> GitLab4J-API release 4.12.6 has been released that properly handles a response when "message" is an array.
> 
> Please verify and close this issue when you have a chance.

Has been resolved, thank you
