### ISSUE TITLE
NotificationSettingsApi: the event key has an extra e

### ISSUE THREAD

**Issue by LayYX** [gitlab4j/gitlab4j-api#437]
Almost all event key have an extra e。
For example, it should be "new_issue", but it is now "new_issuee"

![image](https://user-images.githubusercontent.com/22714222/65653240-0a342480-e047-11e9-910e-3e1b3510b673.png)

**Comment by gmessner** [comment]
@LayYX Can't believe this was missed.  It has been fixed and a release will be done tomorrow.

**Comment by gmessner** [comment]
@LayYX Release 4.12.7 is now available with this fix.

Please verify and close when you have the time.

**Comment by gmessner** [comment]
@LayYX 
Since this has been fixed I am closing this issue.  If you find any problems with the fix please feel free to re-open.
