### ISSUE TITLE
Unable to post merge request discussion

### ISSUE THREAD

**Issue by ManuZiD** [gitlab4j/gitlab4j-api#442]
Hi,

I want to post a discussion on a merge request.

I have the following call:

```
gitLabApi.discussionsApi.createMergeRequestDiscussion(projectId, mergeRequestIid, body,
                    Date.from(Instant.now()), null, Position().apply {
                positionType = Position.PositionType.TEXT
                newLine = line
                baseSha = mergeRequestMetaData.baseSha
                headSha = mergeRequestMetaData.headSha
                startSha = mergeRequestMetaData.startSha
                oldPath = fullPath
                newPath = fullPath
            })
```

every time I execute this I get the following error:

`400 (Bad request) "Note {:line_code=>["can't be blank", "must be a valid line code"]}"`

I'm a bit confused about that, where the parameter `line_code` come from. I can't find them in the documentation: https://docs.gitlab.com/ee/api/discussions.html#create-new-merge-request-thread

I'm doing something wrong, maybe wrong method call or is there a bug?

**Comment by gmessner** [comment]
@ManuZiD 
```line_code``` is not a parameter that get's passed in, has something to do with the diffs.  I found several issues online related to this and is likely not anything that this library is causing.

Can you see if you can do this manually using the GitLab UI?

**Comment by ManuZiD** [comment]
Hi @gmessner thanks for the quick response.

Today I played something around with the ui and postman. I figured out that I haven't the right path in `position[old_path]` and `position[new_path]`. I missed the `src/main/java` part. Sorry my bad. The plugin works like a charm.
