### ISSUE TITLE
Add API call to /api/v4/license

### ISSUE THREAD

**Issue by jabby** [gitlab4j/gitlab4j-api#443]
Hello, 

First, thanks for the amazing work on this library. It's really useful. 

I would like to use some of standalone API of GitLab. I realized that some of them are not covered by the current version of `gitlab4j-api`. Maybe it's intended and I'm ok with that. Neverless, I would like to know if this is in the roadmap to add a call to `/api/v4/license`. 

I know it's not available on gitlab.com but I think it can be useful for users like me with a self-managed version of GitLab. 

You can find some documentation here: 
* https://docs.gitlab.com/ee/api/api_resources.html#standalone-resources
* https://docs.gitlab.com/ee/api/license.html

Thanks for your answer.

**Comment by gmessner** [comment]
@jabby 
What you have uncovered is that GitLab has actually changed the API, this library currently has the ```LIcensesApi``` but that has now been moved from ```/licenses``` to ```/templates/licenses```.  What they have done is created a new API on the ```/license``` path which is what you are asking for.  

I will put both fixing the existing ```LicensesApi``` and adding the ```LicenseApi``` on the roadmap and will schedule both for the next release, which will be released no later than Sunday 10/6/2019.

**Comment by jabby** [comment]
@gmessner Thanks for your quick answer. 

If you need some help to test your work, I am available.

**Comment by gmessner** [comment]
@jabby 
I will need some help to verify the license API that you are requesting, as I do not have a license for GitLab.

I will let you know when it is released.

**Comment by gmessner** [comment]
@jabby GitLab4J-API Release 4.12.9 has been completed.

If you could verify the ```LicenseApi``` functionality and close this issue I would appreciate it.

**Comment by jabby** [comment]
I will try the new release tomorrow.

**Comment by jabby** [comment]
Sorry for the delay. It works as expected. Thanks again for your work.
