### ISSUE TITLE
UserApi constructor is not public

### ISSUE THREAD

**Issue by TamasNeumer** [gitlab4j/gitlab4j-api#450]
I'm unable to get an instance of UserApi. Constructor is package private. Was this intentional? (Almost all the other API classes have public constructors.)

```java
public class UserApi extends AbstractApi {

    private boolean customAttributesEnabled = false;

    UserApi(GitLabApi gitLabApi) {
        super(gitLabApi);
    }
   //...
```

**Comment by gmessner** [comment]
@TamasNeumer 
Not sure why ```UserApi``` only has a package scoped constructor, this has been corrected in the code.  This is much too small of a change to do a release, will do a release when there are more updates.

In the meantime is there a reason you can't use the ```getUserApi()``` method in your ```GitLabApi``` instance?

**Comment by TamasNeumer** [comment]
Sure I can.

As you have committed the fix to the master branch I would close the ticket.

Kind regards,
Tamas

**Comment by gmessner** [comment]
@TamasNeumer 
Release 4.12.14 is now available with this change.

**Comment by TamasNeumer** [comment]
Thank you!
