### ISSUE TITLE
Event getTargetType() always return null.

### ISSUE THREAD

**Issue by ManOfGod** [gitlab4j/gitlab4j-api#454]
I'm using this library for my app integration but during my testing. I always noticed that getTargetType() always return null but when I tried accessing the api through postman the "target_type" contains a value.

**Comment by gmessner** [comment]
@ManOfGod 
How are you creating instances of ```Event```?  This library requires the use of the ```ObjectMapper``` that is in ```org.gitlab4j.api.util.JacksonJson``` to properly deserialize enums.

**Comment by ManOfGod** [comment]
@gmessner 
This is how I did it:
`
gitlabApi = new GitLabApi(getApiUrl(), getApiToken());

List<Event> events = gitlabApi.getEventsApi().getProjectEvents(project.getId(), null, null,
                            new Date(), getStartDate(), SortOrder.DESC);

`

**Comment by gmessner** [comment]
@ManOfGod 
What version of this library are you using?
Is fastjson a dependency in your application?

**Comment by ManOfGod** [comment]
I'm using version 4.12.12 and no I don't have a fastjson dependency.

**Comment by gmessner** [comment]
@ManOfGood  
Can you provide me the URL you are using in Postman (blackout any sensitive info)?

**Comment by ManOfGod** [comment]
https://gitlab.com/api/v4/events?private_token="PRIVATE_TOKEN"

**Comment by gmessner** [comment]
@ManOfGod 
This has been fixed in Release 4.12.15.  When you have a chance please verify and close this issue.

**Comment by gmessner** [comment]
@ManOfGod 
Since the fix has been released I'm going to go ahead and close this issue.  If you find any problems with the fix please feel free to re-open.
