### ISSUE TITLE
RepositoryFile is missing content_sha256 field

### ISSUE THREAD

**Issue by etiennemaillard** [gitlab4j/gitlab4j-api#455]
The GitLab API doc show that the call `GET /projects/:id/repository/files/:file_path` includes the field `content_sha256` which is not present on `RepositoryFile` object.

**Comment by gmessner** [comment]
@etiennemaillard 
The ```content_sha256``` field has been added by GitLab after this was implemented.  The field has been added and checked in.  A release will be done within the next week, will let you know when it has been released.

**Comment by gmessner** [comment]
@etiennemaillard 
Release 4.12.15 is now available with this fix. When you have a chance please verify and close this issue.

**Comment by gmessner** [comment]
@etiennemaillard 
Since this has been released I'm going to go ahead and close this issue, if you find any problems with the fix please feel free to re-open.
