### ISSUE TITLE
Gitlab4J is missing Constants.MergeRequestState.LOCKED ("locked") state

### ISSUE THREAD

**Issue by alexmnyc** [gitlab4j/gitlab4j-api#457]
Gitlab4J is missing Constants.MergeRequestState.LOCKED ("locked") state

During pre-receive hook on merge request, the merge request status is in "locked" state and using static API it is impossible to query for that merge request.

**Comment by gmessner** [comment]
@alexmnyc 
I've added the LOCKED value to MergeRequestState.  This will be released on Monday 10/28/2019, will let you know when the release is available.

**Comment by alexmnyc** [comment]
Thank you. There is one more issues I noticed with discussion api implementation. I'll create a separate issue for it.

**Comment by alexmnyc** [comment]
Please see https://github.com/gitlab4j/gitlab4j-api/issues/458

**Comment by alexmnyc** [comment]
Also, is there a reason why there is no async client implementation?

**Comment by gmessner** [comment]
Release 4.12.15 is now available. When you have a chance please verify and close this issue.

Concerning async support, when this library was originally released AsyncResponse was not available, to add support for it would be a major amount of work so it will likely never be added.

**Comment by alexmnyc** [comment]
Will check. Thank you

**Comment by gmessner** [comment]
@alexmnyc 
I'm going to go ahead and close this.  Please feel free to reopen if you find any problems with the change.
