### ISSUE TITLE
Discussion API is not following the spec

### ISSUE THREAD

**Issue by alexmnyc** [gitlab4j/gitlab4j-api#458]
```
Discussion createMergeRequestDiscussion(Object projectIdOrPath, Integer mergeRequestIid,
            String body, Date createdAt, String positionHash, Position position)
```

https://docs.gitlab.com/ee/api/discussions.html#create-new-merge-request-thread

Attribute | Type | Required | Description
-- | -- | -- | --

position | hash | no | Position when creating a diff note
-- | -- | -- | --

You can see that Position object is optional, yet, Gitlab4J forces you to create one.

**Comment by gmessner** [comment]
@alexmnyc 
Actually it is following the spec, the position you are referring to in the docs, is the ```String postionHash``` parameter in the ```createMergeRequestDiscussion()``` method which is optional.  The ```Position postion``` parameter in ```createMergeRequestDiscussion()``` provides the following information and some of it is required:

Attribute | Type | Required | Description
-- | -- | -- | --
position[base_sha] | string | yes | Base commit SHA in the source branch
position[start_sha] | string | yes | SHA referencing commit in target branch
position[head_sha] | string | yes | SHA referencing HEAD of this merge request
position[position_type] | string | yes | Type of the position reference’, allowed values: ‘text’ or ‘image’
position[new_path] | string | no | File path after change
position[new_line] | integer | no | Line number after change (for ‘text’ diff notes)
position[old_path] | string | no | File path before change
position[old_line] | integer | no | Line number before change (for ‘text’ diff notes)
position[width] | integer | no | Width of the image (for ‘image’ diff notes)
position[height] | integer | no | Height of the image (for ‘image’ diff notes)
position[x] | integer | no | X coordinate (for ‘image’ diff notes)
position[y] | integer | no | Y coordinate (for ‘image’ diff notes)

**Comment by alexmnyc** [comment]
POST https://gitlab.example.com/api/v4/projects/5/merge_requests/11/discussions?body=comment

Is sufficient to post a comment but Gitlab4J does not allow null objects for Position

**Comment by gmessner** [comment]
@alexmnyc 
This library tries as best as possible to follow the documentation and the documentation indicates that the following are required: ```position[base_sha]```, ```position[start_sha]```, ```position[head_sha]```, ```position[position_type```

I did just test it and as you have discovered those attributes are not actually required.  If you could submit an issue to GitLab concerning this incorrect documentation, I will be more than happy to make this change.

**Comment by gmessner** [comment]
@alexmnyc 
I've decided to go ahead and make the position parameter optional.  When I have time I will submit an issue with GitLab about the documentation being incorrect.  Please verify and close when you have time.

**Comment by alexmnyc** [comment]
That is awesome! Thank you. It looks good.
