### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Lasering** [gitlab4j/gitlab4j-api#459]
It would be helpful to support Group and Project Badges:

https://docs.gitlab.com/ee/api/group_badges.html
https://docs.gitlab.com/ee/api/project_badges.html

Thanks in advance.

**Comment by gmessner** [comment]
@Lasering 
```ProjectApi``` already has support for the Project Badges API, it will be quite simple to add Group Badges API support to the ```GroupApi```, will include in the next release.

**Comment by gmessner** [comment]
@Lasering 
Release 4.12.15 is now available with both Group and Project badges API support.  When you have a chance please verify and close this issue.

**Comment by gmessner** [comment]
@Lasering 
Since this functionality has been released I am closing this issue.  If you find any problems feel free to re-open.

**Comment by Lasering** [comment]
Sorry for taking so long to respond.

I didn't do my homework properly. I saw the group badges were not supported and assumed project badges weren't supported as well.

Once again, lightning speed adding a new feature. :1st_place_medal: :clap: 

I've already tested it, and its working perfectly. Thank you.
