### ISSUE TITLE
Protected branches API methods accept Integer instead of Object for projectIdOrPath

### ISSUE THREAD

**Issue by SamerAdra** [gitlab4j/gitlab4j-api#461]
There are a few methods in ProtectedBranchesApi that accept Integers to identify a project, but the intention of the code is that it should accept an Object that could be either a project ID or path. This is clear from the Javadocs and variable name (projectIdOrPath), and it would be consistent with the rest of gitlab4j.

The methods with the issue are unprotectBranch and both overloads of protectBranch.

**Comment by gmessner** [comment]
@SamerAdra This has been fixed and is in release 4.12.16.  Please verify and close this issue when you have time.

**Comment by SamerAdra** [comment]
Worked as expected (tested both protect and unprotect methods). Thanks!
