### ISSUE TITLE
I'm can't use getStatistics() getStorageSize() methods

### ISSUE THREAD

**Issue by ramirissilva** [gitlab4j/gitlab4j-api#475]
I need to get the statistics of all repositories, but I receive error when I run the program.
Help me

error:
Exception in thread "main" java.lang.NullPointerException
	at gitlabConsumerRest.main(gitlabConsumerRest.java:33)

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.gitlab4j.api.GitLabApi;
import org.gitlab4j.api.GitLabApiException;
import org.gitlab4j.api.Pager;
import org.gitlab4j.api.ProjectApi;
import org.gitlab4j.api.models.Project;
import org.gitlab4j.api.models.Group;

public class gitlabConsumerRest {
    public static void main(String[] args) throws Exception { 	
    	int Projects = 0;

		GitLabApi gitLabApi = new GitLabApi("XXXXXXXXXX", "XXXXXXXXXXXXXXX");
		Pager<Project> projectPager = gitLabApi.getProjectApi().getProjects(10);			
		
		DateFormat srcDf = new SimpleDateFormat("dd/MM/yyyy");
		
		while (projectPager.hasNext()) {
		    for (Project project : projectPager.next()) {
		    	
		    	Date dateCreatedAt = project.getCreatedAt();
		    	String dateCreatedAtConverted = srcDf.format(dateCreatedAt);
		    	
		    	Date dategetLastActivityAt = project.getLastActivityAt();
		    	String dategetLastActivityAtConverted = srcDf.format(dategetLastActivityAt);
		    	System.out.println(project.getId() + "|" + project.getHttpUrlToRepo() + "|" + project.getName() + "|" + dateCreatedAtConverted + "|" + dategetLastActivityAtConverted + "|" + project.getDescription());
		    	**System.out.println(project.getStatistics().getStorageSize());**
		        Projects++;
		        
		    }
		}
		System.out.println("TOTAL: " + Projects);
		}
    }

**Comment by gmessner** [comment]
@ramirissilva 
The returned ```Project``` instances do not include statistics unless you request them, this can be done by making the following change:
```
...
import org.gitlab4j.api.models.ProjectFilter;
...

ProjectFilter filter = new ProjectFilter().withStatistics(true);
Pager<Project> projectPager = gitLabApi.getProjectApi().getProjects(filter, 10);
```

**Comment by ramirissilva** [comment]
@gmessner 
Worked perfectly! Thank you!!!
