### ISSUE TITLE
Add tasks to Issues model

### ISSUE THREAD

**Issue by pismy** [gitlab4j/gitlab4j-api#483]
GitLab issues now have 3 new fields related to tasks management:

* `has_tasks` (boolean)
* `task_status` (String)
* `task_completion_status` (Object)

**Comment by gmessner** [comment]
@pismy 
I have also identified 3 additional new fields:
* ```upvotes``` (Integer)
* ```downvotes``` (Integer)
* ```merge_requests_count``` (Integer)

I will add the 6 new fields and do a release this weekend.

**Comment by gmessner** [comment]
@pismy 
Release 4.14.5 is now available with the 6 new fields added.  Please verify and close this issue when you have time.

**Comment by pismy** [comment]
Many thanks.

**Comment by gmessner** [comment]
@pismy 
Since this enhancement has been released, I am closing this issue.  Please feel free to reopen if you find any problems with the implementation.
