### ISSUE TITLE
Support rebase for merge request API

### ISSUE THREAD

**Issue by blacksteed232** [gitlab4j/gitlab4j-api#484]
Hi,

It seems like the Gitlab Merge Request API [has support for rebasing](https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request). It would be really great if we can have this in gitlab4j as well.

Thank you so much for this great library!

**Comment by gmessner** [comment]
@blacksteed232 
This functionality has been added in 4.14.6.  See the following for more info:
```
MergeRequestApi.rebaseMergeRequest(Object projectIdOrPath, Integer mergeRequestIid)
MergeRequestApi.getRebaseStatus(Object projectIdOrPath, Integer mergeRequestIid)
```
When you have a chance please verify and close this issue.

**Comment by blacksteed232** [comment]
@gmessner Thank you so much!! I will check this out in a few days and close this issue then.
