### ISSUE TITLE
AbstractMethodError is thrown when getting projects

### ISSUE THREAD

**Issue by ManOfGod** [gitlab4j/gitlab4j-api#485]
I keep on getting this error:
`java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;`
when executing `projects = gitlabApi.getProjectApi().getMemberProjects();`

**Comment by gmessner** [comment]
@ManOfGod 
I am not able to reproduce this issue.  I suspect you may have an invalid GitLab host URL.  Can you provide the following:
1) The GitLab host URL (you can mask the hostname if needed)
2) GitLab4J-API version
3) GitLab server version

**Comment by ManOfGod** [comment]
1. https://gitlab.com
2. '4.14.5'
3. v4?
4. 1.8

**Comment by gmessner** [comment]
@ManOfGod 
I suspect that your project is using an early version of Jersey Client, Jersey Apache Connector,  or JAX-RS.  Make sure you have at least these versions in your dependencies:
```
jersey-client:2.29.1
jersey-apache-connector:2.29.1
jakarta.ws.rs-api:2.1.6
```

**Comment by gmessner** [comment]
@ManOfGod 
Have not heard any response, are you still having issues?  If not please close this issue.

**Comment by ManOfGod** [comment]
Still having the issue, so I ended up using UNIREST.

**Comment by gmessner** [comment]
@ManOfGod 
I have thoroughly manually tested this and there are integration tests that test it too, so I am certain that it is a dependency issue.

Sorry I cannot help you with this, can we go ahead and close this issue?

**Comment by ManOfGod** [comment]
Yeah sure :)

**Comment by xavierhardy** [comment]
In my case, it was a conflict with `com.sun.jersey` imported as a transitive dependency by another API client. Exclude the group/org `com.sun.jersey` in your build project.

**Comment by Jalr4ever** [comment]
I got this issue too, the same as dependency conflict, use 「dependency analyzer」 search「 jersey」, and exclude all dependencies which not behind gitlab4j will help this case
