### ISSUE TITLE
discussionId not being used to  resolve merge request discussion

### ISSUE THREAD

**Issue by matruskan** [gitlab4j/gitlab4j-api#495]
It looks like `discussionId` is not being used by `resolveMergeRequestDiscussion()`.

https://github.com/gitlab4j/gitlab4j-api/blob/897e1db03bfb041a6fae7cce94a19d75e01ab94a/src/main/java/org/gitlab4j/api/DiscussionsApi.java#L349-L355

Anyway, thank you all for this library!

**Comment by gmessner** [comment]
@matruskan 
This has been fixed and will be released later today, will let you know when the release is available.

**Comment by gmessner** [comment]
@matruskan GitLab4J-API Release 4.14.11 is available with this fix, please verify and close this issue when you have time.

**Comment by matruskan** [comment]
Looks like it's fixed! Thank you!
