### ISSUE TITLE
Improvement: CommitsApi.getDiff() supports `per_page ` parameter

### ISSUE THREAD

**Issue by annguyen-qh** [gitlab4j/gitlab4j-api#497]
Please supports the `per_page ` parameter when listing diffs of a commit. Currently, the default page_size from Gitlab is 20, I can't bypass this size limit of the returned list.

**Comment by gmessner** [comment]
This library is in the process of deprecating the methods that take per_page and a page_number, we provide this support via Pager and Java Stream.  I have added these methods to the ```CommitsApi```.  Additionally, the ```getDif()``` method that returns ```List<Diff>``` now returns all the Diffs regardless of the count.

This will be released later today, will let you know when it is available.

**Comment by gmessner** [comment]
@annguyen-qh GitLab4J-API Release 4.14.11 is available with this functionality, please verify and close this issue when you have time.

**Comment by annguyen-qh** [comment]
Thanks for the great work!
I’ve upgraded to 4.14.11 and it worked as expected!!
