### ISSUE TITLE
Implement the Merge Request Pipelines methods

### ISSUE THREAD

**Issue by arrowman53** [gitlab4j/gitlab4j-api#500]
There are two Merge Request API requests that I could not find in the gitlab4j-api library:
- [List MR pipelines](https://docs.gitlab.com/ce/api/merge_requests.html#list-mr-pipelines)
- [Create MR Pipeline](https://docs.gitlab.com/ce/api/merge_requests.html#create-mr-pipeline)

Could these also be added as methods in the MergeRequestApi?

Thanks in advance.

**Comment by gmessner** [comment]
@arrowman53 
I have added the merge request pipeline functionality.  The changes are checked in and a release will be done in a few days.  Will let you know when the release is available.

**Comment by gmessner** [comment]
@arrowman53 
The merge request pipeline functionality has been added to the ```MergrRequestsApi``` and is available in GitLab4J-API Release 4.14.14.  Please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@arrowman53 
Since this functionality has been released we are closing this issue.  If you run into any problems with it feel free to reopen this issue.
