### ISSUE TITLE
Allow getting the list of merge requests associated with a commit

### ISSUE THREAD

**Issue by blacksteed232** [gitlab4j/gitlab4j-api#502]
Hi, 

Gitlab Commit API has support for [getting the list of merge requests associated with a commit](https://docs.gitlab.com/ee/api/commits.html#list-merge-requests-associated-with-a-commit). It would be really great if we can have this in gitlab4j as well.

Thank you so much!

**Comment by blacksteed232** [comment]
@gmessner Thank you so much!

**Comment by gmessner** [comment]
@blacksteed232 
Still need to add some integration tests for this, should have that done and will be doing a release tomorrow.

**Comment by gmessner** [comment]
@blacksteed232 
GitLab4J-API Release 4.14.15 is now available.  Please verify the new functionality and close this issue when you have time.

**Comment by blacksteed232** [comment]
@gmessner Thank you, it works like charm!
