### ISSUE TITLE
support returning Pager for getCommitRefs

### ISSUE THREAD

**Issue by blacksteed232** [gitlab4j/gitlab4j-api#505]
Hi, we just bumped into a use case (weird one) that the number of `commit refs` returned is greater than the default page size (96) of gitlab4j so I thought it would make sense to have a method that returns a Pager of `commit refs` rather than a list. That would be great!

UPDATE: Attempted to do this with a pull request #506

**Comment by gmessner** [comment]
@blacksteed232 I have merged your pull request and added additional ```getCommitRefs()```.  The ```getCommitRefs()``` methods that return ```List<CommitRef>``` now return a List of **all** CommitRefs regardless of the count.

GitLab4J-API Release 4.14.16 is now available, please verify and close this issue when you have time.

**Comment by blacksteed232** [comment]
@gmessner do you know how long it usually takes to appear on maven central?

**Comment by gmessner** [comment]
It can take up to 24 hours depending on activity.

**Comment by gmessner** [comment]
@blacksteed232 I just checked and 4.14.16 is available, it is just not indexed yet.  I believe if you specify 4.14.16 in your pom or build.gradle file it will find it.

**Comment by blacksteed232** [comment]
@gmessner looks good to me. Closing this one now. Thank you!
