### ISSUE TITLE
Cannot access subgroups

### ISSUE THREAD

**Issue by jgsuess** [gitlab4j/gitlab4j-api#512]
The following works for me, and is probably a bug.
```java
AssertIsNull(new GitLabApi("serverUrl","token").getGroupApi().getGroup("hasSubGroups").getProjects());
```
I assume this is due to the fact that there is no way to pass the [`include_subgroups`](https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects) flag.

I also get the same result (no projects listed) when I query the groups api with the subgroups ID.
I can get the subgroup, but no projects contained in it.

A sample of how to crawl subgroups would be appreciated.

Note that this should also work with private subgroups and servers.

**Comment by gmessner** [comment]
@jgsuess First off you cannot call ```getProjects()``` on a ```Group``` instance you must pass the ```Group``` instance into the ```getProjects(group)``` method as follows:
```
GitLabApi gitLabApi = GitLabApi("serverUrl", "token");
List<Project> projects = gitLabAPi.getGroupApi().getProjects("group-path");
```

If you want to include the projects from the sub groups you would do this:
```
GitLabApi gitLabApi = GitLabApi("serverUrl", "token");
GroupProjectsFilter filter = new GroupProjectsFilter().withIncludeSubGroups(true);
List<Project> projects = gitLabAPi.getGroupApi().getProjects("group-path", filter);
```
BTW, ```GroupProjectsFilter``` has many other things that it can filter on.

**Comment by jgsuess** [comment]
Excellent. Thanks for the help.. My problem was that I had not understood that this API is a 1:1 translation of the REST api. That is the classes are holders and the guarantees they can make w.r.t. data really depend on the call made before. And you cannot expect client-side integrities like `equals()`, `hashCode()` or `Comparable` implementations.

**Comment by gmessner** [comment]
@jgsuess We will actually be implementing ```equals()``` and ```hashCode()``` methods in the model classes soon, see Issue #494 .  I actually asked the person that submitted the issue to submit it.  I hope to be finished with this in the next month or so.
