### ISSUE TITLE
LinkHeader

### ISSUE THREAD

**Issue by samuelfac** [gitlab4j/gitlab4j-api#519]
Company I work for, has "GitLab Community Edition 8.3.2" (I know, a _little_ old, but I can't update), 
I'm trying to use the library, but the pagination part doesn't work, because the return was made in this model: https://www.w3.org/wiki/LinkHeader

Is there an old version of the library that works with this pagination model?

**Comment by gmessner** [comment]
@samuelfac Unfortunately, the Pager mechanism was not added until 7/2017 when GitLab was at version 9.2 so this library does not support pagination for GitLab 8.
