### ISSUE TITLE
Proposal for pagers exception

### ISSUE THREAD

**Issue by jflefebvre06** [gitlab4j/gitlab4j-api#522]
Actually, pagers and others lamda functions throw runtime exception and we lost http status, stask, ....

Proposal, throw a runtime that wrap a GitlabApiException.

**Comment by gmessner** [comment]
@jflefebvre06  I'm not a big fan of hiding checked exceptions, but there are some ways to keep your lambda code clean and concise and have a RuntimeException wrap the GitLabApiException, check out this library:
https://github.com/pivovarit/throwing-function

**Comment by jflefebvre06** [comment]
Sorry, the only case you return a runtime without a gitlabexception is RuntimeException(`Cannot determine ID or path from null object`)
