### ISSUE TITLE
Deserialization error when merge request closes external issue

### ISSUE THREAD

**Issue by krische** [gitlab4j/gitlab4j-api#528]
When requesting the [list of issues that close on merge](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-will-close-on-merge) of a merge request, if using an external issue tracker (e.g. Jira), it is possible for it to return an object where the `id` is of type `String` instead of `Integer`. This causes a deserialization exception when trying to deserialize the response into an `Issue` instance.

**Comment by gmessner** [comment]
@krishe That is a tricky one, will need to create a custom deserializer for this field and add a pseudo field called ```externalId``.  This way it will be easy to determine that the issue is external.  Because the ```id``` being a String only infers this.  adding the ```externalId``` field will be a way to make it explicit.  Wish GitLab would have done that in the results, maybe an issue should be submitted to GitLab to correct this.

**Comment by gmessner** [comment]
@krische I have added support for the String based external ID on issues and have released version 4.14.19 with this functionality.

Please verify and close when you have time.

**Comment by krische** [comment]
Works great!
