### ISSUE TITLE
Example of usage - List all jobs from other user

### ISSUE THREAD

**Issue by jacksonpradolima** [gitlab4j/gitlab4j-api#529]
Hello,
I am developing a research concerning CI testing, and I need to download the jobs. However, I am not the owner of the project.
How can I access and download all jobs?

Thanks in advance

**Comment by gmessner** [comment]
@jacksonpradolima 
You would need to get all projects and iterate over each project getting the jobs for a project.  The following example assumes you have a valid ```GitLabApi``` instance named ```gitLabApi```:
```
// Get a list of accessible projects 
public List<Project> projects = gitLabApi.getProjectApi().getProjects();
for (Project project : projects) {

    // Get a list of jobs for the project
    List<Job> jobs = gitLabApi.getJobApi().getJobs(project);
    ...
}

**Comment by jacksonpradolima** [comment]
Thanks
