### ISSUE TITLE
RepositoryFileApi.getFile throws validation error on branch name containing curly braces

### ISSUE THREAD

**Issue by SamerAdra** [gitlab4j/gitlab4j-api#530]
When attempting to call RepositoryFileApi.getFile where the branch name contains blahblah{profileId}, the method throws an exception with the message "The template variable 'profileId' has no value."
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:604)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:182)
	at org.gitlab4j.api.RepositoryFileApi.getFile(RepositoryFileApi.java:166)

The validation error is coming from org.glassfish.jersey.core.UriTemplate method createUriComponent.
Perhaps it just needs to be URL encoded?
Using 4.12.18.

**Comment by gmessner** [comment]
@SamerAdra You are correct, the ref (branch) should be URL encoded, it's a simple fix and will be included in the next release.

**Comment by gmessner** [comment]
@SamerAdra Release 4.14.20 is now available with this fix.

**Comment by SamerAdra** [comment]
This particular issue is fixed, but now I get the same thing in the pipeline api. Not sure if you want me to proliferate issues for the same root cause.

org.gitlab4j.api.GitLabApiException: The template variable 'segmentOfMyBranchName' has no value

	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:215)
	at org.gitlab4j.api.Pager.<init>(Pager.java:92)
	at org.gitlab4j.api.PipelineApi.getPipelines(PipelineApi.java:206)
	at org.gitlab4j.api.PipelineApi.getPipelinesStream(PipelineApi.java:171)

**Comment by gmessner** [comment]
@SamerAdra I'll created an issue (#531) to do a sweep of things to identify all places this might be a problem.  If this particular issue is fixed go ahead and close it.

**Comment by gmessner** [comment]
@SamerAdra I've fixed all the ref issues that I could locate and have released 4.14.22 with these fixes.

**Comment by SamerAdra** [comment]
All the APIs I am using are now working in this scenario. Thanks!
