### ISSUE TITLE
How to set timeout

### ISSUE THREAD

**Issue by ssy352959096** [gitlab4j/gitlab4j-api#532]

**Comment by gmessner** [comment]
@ssy352959096 We just added a simple way to do this in version 4.14.21:
```java
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.com", "YOUR_PERSONAL_ACCESS_TOKEN", proxyConfig);

// Set the connect timeout to 1 second and the read timeout to 5 seconds
gitLabApi.setRequestTimeout(1000, 5000);
```
I am wondering why you need to set it, are you having problems with something?

**Comment by gmessner** [comment]
@ssy352959096 Since this has been released I am closing this issue. If you have problems with the implementation please re-open this ticket.
