### ISSUE TITLE
  How to get the commit record of a branch？（excluding the commit record before the branch is created.）

### ISSUE THREAD

**Issue by shxiq01** [gitlab4j/gitlab4j-api#534]
I want to get the commit records of a branch. It seems that the API gets all the commit records, including those of other branches before branch creation,or can I get the creation time of the branch?

**Comment by shxiq01** [comment]
@gmessner excuse me?

**Comment by gmessner** [comment]
@shxiq01 There is no way to determine when a branch is created and a branch will contain all the commits of its parent. The branch creation date is an often requested feature of Git but is not provided.

**Comment by shxiq01** [comment]
> @shxiq01 There is no way to determine when a branch is created and a branch will contain all the commits of its parent. The branch creation date is an often requested feature of Git but is not provided.

Well, thank you for your support!
