### ISSUE TITLE
How do I use concurrent requests?

### ISSUE THREAD

**Issue by magaofei** [gitlab4j/gitlab4j-api#535]
For example, when I use `getCommits()` to get the data, the data often has many pages, and when using the `all()` method, it is synchronized. I want to use concurrent requests. Is there a way to do this?
Also, is the `page()` method thread-safe?

**Comment by gmessner** [comment]
@magaofei You cannot make concurrent request using the ```Pager``` class, it is not the intention of it.  And no the ```page()``` method is not thread safe.

**Comment by magaofei** [comment]
> @magaofei You cannot make concurrent request using the `Pager` class, it is not the intention of it. And no the `page()` method is not thread safe.

Thank you. Can subsequent thread-safe classes be provided? We need this

**Comment by gmessner** [comment]
@magaofei Unfortunately, the GitLab API paging mechanism is not intended on being accessed in a concurrent way, there would be no guarantee of the validity for the returned results, so this library will not allow it to be used that way.
