### ISSUE TITLE
how can i get label type discussion

### ISSUE THREAD

**Issue by zhangyanglei** [gitlab4j/gitlab4j-api#537]
![image](https://user-images.githubusercontent.com/30100164/77308974-ca6ca200-6d36-11ea-983e-b49d0aa736a5.png)

i want get label discussion update time, but when i user discussionApi i only get 2 discussion

**Comment by gmessner** [comment]
@zhangyanglei As it says at the top of this page https://docs.gitlab.com/ce/api/discussions.html:

"This includes system notes, which are notes about changes to the object (for example, when a milestone changes, there will be a corresponding system note). Label notes are not part of this API, but recorded as separate events in resource label events."

You need to use the methods available in ```org.gitlab4j.api.ResourceLabelEventsApi``` to get the info on the labels that are attached to discussions.

**Comment by zhangyanglei** [comment]
👌 i got it， thank you
