### ISSUE TITLE
Add support of group_saml_identity in the GroupApi

### ISSUE THREAD

**Issue by parrot55** [gitlab4j/gitlab4j-api#538]
When using SAML authentication, a call to v4/groups/12345678/members returns group_saml_identity objects (see example below), which are not supported by the current implementation of the GroupApi. For our purposes, we need to access to the extern_uid.

[
  {
    "id": 2,
    "username": "john_doe",
    "name": "John Doe",
    "state": "active",
    "avatar_url": "https://www.gravatar.com/avatar/c2525a7f58ae3776070e44c106c48e15?s=80&d=identicon",
    "web_url": "http://192.168.1.8:3000/root",
    "expires_at": "2012-10-22T14:13:35Z",
    "access_level": 30,
    "group_saml_identity": {
      "provider": "group_saml",
      "extern_uid": "12345678-9abc-def0-1234-56789abcdef0",
      "saml_provider_id": 570
    }
  }
]

Could you please add this feature in the API?

If you prefer, I implemented this support in the Member.java and Identity.java classes and can provide a pull request.

Cheers,
Patrick

**Comment by gmessner** [comment]
@parrot55 I've added support for ```group_saml_identity``` and the associated ```saml_provider_id``` in the ```Identity``` class.  I plan on doing a release on 3/28/2020, if you have an urgent need for it let me know and I'll do a release when asked.

BTW, thanks for the offer of a pull request, but this was a simple enhancement so I just did it.

**Comment by gmessner** [comment]
@parrot55 This support was released last week, could you verify and close this issue when you have time?

**Comment by gmessner** [comment]
@parrot55 Since this was implemented and released over two weeks ago I am closing this issue, if you have any problems with it please feel free to re-open.
