### ISSUE TITLE
Add support for Deploy Token API

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlab4j/gitlab4j-api#539]
GitLab 12.9 introduce Deploy Token API with a documentation available here: https://docs.gitlab.com/ee/api/deploy_tokens.html

**Comment by gmessner** [comment]
@PhilippeVienne This has been released in 4.14.24, please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@PhilippeVienne  Since this functionality has been released for over a week I am closing this issue.
