### ISSUE TITLE
where is  Correspondence with gitlab version

### ISSUE THREAD

**Issue by zhangyanglei** [gitlab4j/gitlab4j-api#540]
i think i user wrong version, because i add a hook but i can not get all property, 
hook send is this
![image](https://user-images.githubusercontent.com/30100164/77820901-c2d73f80-7120-11ea-8f16-bf8710ec8859.png)
but the model is 
![image](https://user-images.githubusercontent.com/30100164/77820912-d7b3d300-7120-11ea-8792-cb67f855b68b.png)
is this?

**Comment by gmessner** [comment]
@zhangyanglei The ```"object_attributes"``` data is in the ```objectAttributes``` property retrieved with ```MergeRequestEvent.getObjectAttributes```, so I'm nuclear at what you are asking.

**Comment by gmessner** [comment]
@zhangyanglei Are you still looking for help with this?

**Comment by gmessner** [comment]
@zhangyanglei I'm going to go ahead and close this issue, if you still need some help with this, feel free to re-open it.

**Comment by zhangyanglei** [comment]
oh, i have solved this, use your json Deserialization can solve it
