### ISSUE TITLE
Search API on projects should allow ref parameter

### ISSUE THREAD

**Issue by ribardo0** [gitlab4j/gitlab4j-api#544]
Hi, 

It is currently not possible in gitlab4j to search in a project on a specific branch.

We should have a method in SearchAPI.java
public List<?> projectSearch(Object projectIdOrPath, ProjectSearchScope scope, String search, String ref)

Documentation in Gitlab API doc : https://docs.gitlab.com/ee/api/search.html#project-search-api
See example using a specific branch in Gitlab API doc : https://docs.gitlab.com/ee/api/search.html#scope-blobs

Thanks in advance,

Olivier

**Comment by gmessner** [comment]
@ribardo0 Release 4.14.25 is available with this PR, please verify and close when you have time.

**Comment by ribardo0** [comment]
Works perfectly fine... unfortunately BranchesAPI (https://docs.gitlab.com/ee/api/branches.html) is not available in Gitlab4J, I will open another issue
