### ISSUE TITLE
PushData miss commitTitle property

### ISSUE THREAD

**Issue by magaofei** [gitlab4j/gitlab4j-api#546]
org.gitlab4j.api.models PushData is missing the `commitTitle` field, and why is the commit_count field not named `commitCount`?

https://docs.gitlab.com/ee/api/events.html
```json
"push_data": {
      "commit_count": 1,
      "action": "pushed",
      "ref_type": "branch",
      "commit_from": "50d4420237a9de7be1304607147aec22e4a14af7",
      "commit_to": "c5feabde2d8cd023215af4d2ceeb7a64839fc428",
      "ref": "master",
      "commit_title": "Add simple search to projects in public area"
    },
```

**Comment by gmessner** [comment]
@magaofei 
```commit_title``` is a recent addition, GitLab often adds fields and really doesn't have a spec other than reviewing the docs to see that something has changed, so we rely on users to inform us that new fields have been added, so thanks for letting us know.  Whenever we update a model we audit it to make sure it is correct.

As far as ```commit_count``` not being camel-cased, that is simply a bug.

Both of these will be corrected and in the next release.

**Comment by gmessner** [comment]
@magaofei Release 4.14.25 is available with this fix, please verify and close when you have time.
