### ISSUE TITLE
Update getting pipelines parameters

### ISSUE THREAD

**Issue by smallcreep** [gitlab4j/gitlab4j-api#547]
* Add `updated_at` ordering to getting pipelines.
* Add parameter `updated_after`.
* Add parameter `updated_before`.

**Comment by gmessner** [comment]
@smallcreep The above has been addressed in GitLab4J-API release 4.14.26

We've added methods in the ```PipelineApi``` that take a ```PipelineFlter``` as a parameter.  ```PipelineFilter``` contains fluent methods to set all of the parameters when fetching the merge requests.

Please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@smallcreep Since this has been released for 2 weeks I'm closing this issue.  If you run into any problems feel free to re-open this issue.

**Comment by smallcreep** [comment]
@gmessner Sorry. I check it. It works. Thank you.
