### ISSUE TITLE
get mergeRequestList without projectId

### ISSUE THREAD

**Issue by zhangyanglei** [gitlab4j/gitlab4j-api#550]
when i set a mergeRequestFilter only have search, i can not get anything
![image](https://user-images.githubusercontent.com/30100164/78685806-da82a500-7924-11ea-869b-deb9d3f7ff1c.png)
but when i use gitlab origin V4 api i can get somethint i want
this is url
http://{gitlab_host}/api/v4/merge_requests?search=B126089&in=title&per_page=96&page=1

**Comment by gmessner** [comment]
@zhangyanglei I have added an integration test for listing merge requests using a MergeRequestFilter as above and it works correctly.  

My guess would be that the value of  ```search``` might not be correct in your above example.

**Comment by gmessner** [comment]
@zhangyanglei Can this issue be closed?

**Comment by gmessner** [comment]
@zhangyanglei I am closing this issue, if you are still having problems with it please feel free to reopen it.
