### ISSUE TITLE
Jobs returned by the Runners api include project information

### ISSUE THREAD

**Issue by Gaff** [gitlab4j/gitlab4j-api#552]
I'm trying to use this API: https://docs.gitlab.com/ee/api/runners.html#list-runners-jobs

However the Job objects returned don't include the `project` information. Would it be possible to add this?

**Comment by ribardo0** [comment]
Hi,
I just added a pull request to fix this issue.
Olivier

**Comment by gmessner** [comment]
@Gaff  This has been added and released in 4.14,27, please verify and close this issue when you have time.

**Comment by Gaff** [comment]
Sorry, missed this. Looks great - thanks!!
