### ISSUE TITLE
how to use gitlab4j-api   in  gitlab version 8.9?

### ISSUE THREAD

**Issue by HQTB123** [gitlab4j/gitlab4j-api#559]

**Comment by gmessner** [comment]
@HQTB123 Unfortunately, GitLab 8.9 uses GitLab API v3 which is no longer officially supported by this library and support for it has been completely removed from GitLab as of version 11.0

**Comment by gmessner** [comment]
@HQTB123 I am closing this issue, if you have additional related questions please feel free to re-open it.
