### ISSUE TITLE
Is there any implementation to delete job artifacts?

### ISSUE THREAD

**Issue by haroon9** [gitlab4j/gitlab4j-api#561]
I am not able to find the implementation of deleting jobs or job artifacts.

**Comment by gmessner** [comment]
@haroon9 The ```JobApi``` provides the following method:
```
public void deleteArtifacts(Object projectIdOrPath, Integer jobId)
```

**Comment by gmessner** [comment]
@haroon9 I noticed that ```cancleJob()``` was misspelled, this has been corrected and will be in next weeks release.  The misspelled method will remain but will be deprecated.

**Comment by haroon9** [comment]
Thank you for your response.
