### ISSUE TITLE
Implement Merge Request Diff Versions

### ISSUE THREAD

**Issue by vgobbo** [gitlab4j/gitlab4j-api#562]
Could you please look into implementing the [Merge Request Diff Versions](https://docs.gitlab.com/ee/api/merge_requests.html#get-mr-diff-versions) API?

I could not find this API, sorry if it is already implemented.

**Comment by gmessner** [comment]
@vgobbo ```getMergeRequestDiffs()``` methods have been added to provide this functionality:

In MergeRequestApi:
```
public List<MergeRequestDiff> getMergeRequestDiffs(Object projectIdOrPath, Integer mergeRequestIid)
public Pager<MergeRequestDiff> getMergeRequestDiffs(Object projectIdOrPath, Integer mergeRequestIid, int itemsPerPage)
public Stream<MergeRequestDiff> getMergeRequestDiffsStream(Object projectIdOrPath, Integer mergeRequestIid)
```

This is available in release 4.14.28, please verify and close this issue when you have time.
