### ISSUE TITLE
Project getTagList() returns 0

### ISSUE THREAD

**Issue by haroon9** [gitlab4j/gitlab4j-api#563]
```
Project project = gitLabApi.getProjectApi().getProject(3);
		
List<String> tagsList = project.getTagList();
System.out.println(tagsList.size());
```
The expected result should be 4 as per my project. But it returns 0. But if I use '''getTagsApi''':
```
List<Tag> tags = gitLabApi.getTagsApi().getTags(3);
System.out.println(tags.size());
```

I get the expected result. Are these two supposed to be different? Or it should return the same thing?

**Comment by gmessner** [comment]
@haroon9 This library has a 1-to-1 relationship with the GitLab API, and the GitLab API does not return the tags when fetching a project, which can be verified here:  https://docs.gitlab.com/ce/api/projects.html#get-single-project

The reason the ```Project``` has the ```tagList``` property is so the tags can be set when creating and updating a project:
https://docs.gitlab.com/ce/api/projects.html#create-project
https://docs.gitlab.com/ce/api/projects.html#edit-project

As you have discovered the ```TagsApi``` is used to get the tags for a project.
