### ISSUE TITLE
Implement a method returning a list of members for a list of IDs

### ISSUE THREAD

**Issue by parrot55** [gitlab4j/gitlab4j-api#565]
I would be interested to have a method in the GroupApi which would return the members of a group for a given list of user IDs. Something like this:

List<Member> getMembers(String groupOrPath, List<String> listOfIDs)

**Comment by gmessner** [comment]
@parrot55 
This library tries to provide a 1-to-1 relationship with the GitLab API, which does not have that functionality.  This would be better to implement at the application level.

**Comment by parrot55** [comment]
Hi @gmessner 
I think it should be possible using the user_ids attribute of /groups/:id/members. I tried it using Postman. But maybe I don't understand the 1-to-1 requirement you have for the library.
See [https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project)

**Comment by gmessner** [comment]
@parrot55 Sorry, the way the question was worded I thought you were asking for something custom, not for something that is available in the GitLab API.  I will get this added in tomorrows release.

**Comment by gmessner** [comment]
@parrot55 ```getAllMembers()``` methods have been added to provide this functionality:

In ProjectApi:
```
public List<Member> getAllMembers(Object projectIdOrPath, String query, List<Integer> userIds)
public Pager<Member> getAllMembers(Object projectIdOrPath, String query, List<Integer> userIds, int itemsPerPage)
public Stream<Member> getAllMembersStream(Object projectIdOrPath, String query, List<Integer> userIds)
```
In GroupApi:
```
public List<Member> getAllMembers(Object groupIdOrPath, String query, List<Integer> userIds)
public Pager<Member> getAllMembers(Object groupIdOrPath, String query, List<Integer> userIds, int itemsPerPage)
public Stream<Member> getAllMembersStream(Object groupIdOrPath, String query, List<Integer> userIds)
```
Both ```query``` and ```userIds``` parameters are optional and can be ```null```.

This is available in release 4.14.28, please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@parrot55 Since this functionality was released over a week ago I ma closing this issue.  If you run into any issues with the implementation please feel free to reopen it.

**Comment by parrot55** [comment]
Works like a charm. Thanx a lot.
