### ISSUE TITLE
Example using OAuth2 to access GitLab resources on user’s behalf

### ISSUE THREAD

**Issue by bbodenmiller** [gitlab4j/gitlab4j-api#566]
Hoping for an example of how to use OAuth2 to access API on user's behalf.

Looks similar to [`oauth2Login`](https://github.com/gitlab4j/gitlab4j-api/blob/b9338f795dff25a6686e811ed9bd577c657bab37/src/main/java/org/gitlab4j/api/GitLabApi.java#L269) but I don't want to pass in username and password but rather pass them through `/oauth/authorize` endpoint.

**Comment by gmessner** [comment]
@bbodenmiller I do not believe the GitLab API allows you to do this, what they do provide is for a user  to ```sudo`` as another user.  See https://github.com/gitlab4j/gitlab4j-api#usage-examples for how to use ```sudo```

**Comment by bbodenmiller** [comment]
@gmessner https://docs.gitlab.com/ee/api/oauth2.html certainly makes this sound possible...

**Comment by gmessner** [comment]
@bbodenmiller The ```/oauth/authorize``` will display a web page that the user will enter their credentials and authorize the desired access, this will result in a response like this:
```
{
 "access_token": "de6780bc506a0446309bd9362820ba8aed28aa506c71eedbe1c5c4f9dd350e54",
 "token_type": "bearer",
 "expires_in": 7200,
 "refresh_token": "8257e65c97202ed1726cf9571600918f3bffb2544b26e00a61df9897668c33a1"
}
```

The ```access_token``` can the be used to access the API by creating a ```GitLabApi``` instance as follows:
```
GitLabApi gitLabApi = new GitLabApi(yourGitLabUrl, TokenType.OAUTH2_ACCESS, accessToken);
```

Because it will display a web page for username and password entry, you would need to create something on your side that does the OAUT2 flow that calls the ```/oauth/authorize``` endpoint,

**Comment by bbodenmiller** [comment]
@gmessner sure. I guess what I was going for is it would be nice if this library had some way initiate the whole process.

1. generate and handle `state`, provide redirect URI, pass user to `/oauth/authorize`
1. when redirect URI hit validates returned `state`
1. uses `code` to request `access_token`
1. sets up new `GitLabApi` using redirected details
1. handles any necessary token refreshes?

**Comment by gmessner** [comment]
@bbodenmiller Sorry, but what you describe is something that should be done by the application side, it is not something this library is intended to provide.

This is an open source project that accepts contributions, so if you were able to implement what you describe in a generic way (i.e. not tied to a specific web server) I would consider it for inclusion in this library.

**Comment by gmessner** [comment]
@bbodenmiller I am going to go ahead and close this issue, if you still have questions, please feel free to reopen.
