### ISSUE TITLE
Implement support for license and license_url in Project

### ISSUE THREAD

**Issue by carlspring** [gitlab4j/gitlab4j-api#567]
Hi,

Could you please add support for `license_url` and `license` in the `org.gitlab4j.api.models.Project` class?

This will help tools that are using your library to better understand under what license a given project is.

Many thanks in advance!

Martin

**Comment by gmessner** [comment]
@carlspring The ```license``` and ```license_url``` properties have been added to the ```Project``` class and methods have been added to get a project with those populated:
```
public Project getProject(Object projectIdOrPath, Boolean includeStatistics,
	    Boolean includeLicense, Boolean withCustomAttributes)
public Optional<Project> getOptionalProject(Object projectIdOrPath, Boolean includeStatistics,
	    Boolean includeLicense, Boolean withCustomAttributes)
```
This is available in release 4.14.28, please verify and close this issue when you have time.

**Comment by carlspring** [comment]
@gmessner ,

Thanks for your quick fix and release!

Do you have a test case that illustrates how to use this?

**Comment by carlspring** [comment]
This is how I'm trying it:

```java
        GitLabApi gitLabApi = new GitLabApi("http://www.gitlab.com", TOKEN);

        ProjectApi projectApi = new ProjectApi(gitLabApi);
        Project project = projectApi.getProject("carlspring/test-repository",
                                                Boolean.FALSE,
                                                Boolean.TRUE,
                                                Boolean.TRUE);
```

And I'm getting:

```
Exception in thread "main" org.gitlab4j.api.GitLabApiException: Moved Permanently
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:213)
	at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:741)
	at com.carlspring.strongbox.licensing.vcs.GitLabLicenseExtractor.extractLicense(GitLabLicenseExtractor.java:33)
	at com.carlspring.strongbox.licensing.vcs.GitLabLicenseExtractor.main(GitLabLicenseExtractor.java:55)
```

What am I doing wrong?

**Comment by gmessner** [comment]
@carlspring The URL is wrong, should be "https://gitlab.com"

**Comment by carlspring** [comment]
Thank you! This works!

Just wanted to clarify -- are the `license.key` and `license.name` in SPDX format?

**Comment by gmessner** [comment]
@carlspring  Those properties are in whatever format  the GitLab API returns, see  https://docs.gitlab.com/ee/api/projects.html#get-single-project

BTW, when you call ```getProject()``` you can make it a lot cleaner by just passing boolean primitives:
```
Project project = projectApi.getProject("carlspring/test-repository", false, true, true);
```
