### ISSUE TITLE
can i get addedLine and removedLine

### ISSUE THREAD

**Issue by zhangyanglei** [gitlab4j/gitlab4j-api#569]

**Comment by gmessner** [comment]
@zhangyanglei If you can go to https://docs.gitlab.com/ee/api/api_resources.html and let me know what resource you are trying to get those properties from I can help.  Basically I need more context on what resource the addedLine and removedLine prperties belong to.

**Comment by zhangyanglei** [comment]
![image](https://user-images.githubusercontent.com/30100164/81361009-cee6f180-910f-11ea-959c-6cd84efd57ee.png)
@gmessner i want get this but i can not find in the gitlab api docs 
maybe it is in  https://docs.gitlab.com/ee/api/merge_requests.html#get-a-single-mr-diff-version

![image](https://user-images.githubusercontent.com/30100164/81361162-39982d00-9110-11ea-83cb-eebf7fbc710b.png)

**Comment by gmessner** [comment]
@zhangyanglei Release 4.14.29 has added the following methods to the ```MergeRequestApi```:
```
public MergeRequestDiff getMergeRequestDiff(Object projectIdOrPath,
	    Integer mergeRequestIid, Integer versionId)
public Optional<MergeRequestDiff> getOptionalMergeRequestDiff(
	    Object projectIdOrPath, Integer mergeRequestIid, Integer versionId)
```

And the ```CommitsApi``` already had methods to return the diffs for commits:
```
public List<Diff> getDiff(Object projectIdOrPath, String sha)
public Pager<Diff> getDiff(Object projectIdOrPath, String sha, int itemsPerPage)
public Stream<Diff> getDiffStream(Object projectIdOrPath, String sha)
```

**Comment by zhangyanglei** [comment]
@gmessner thank you first, but i want direct get addLine or removeLine, In class DIff, should i get addLine on property diff?
![image](https://user-images.githubusercontent.com/30100164/81793475-00125800-953c-11ea-8129-bafeb4b7270d.png)

**Comment by gmessner** [comment]
@zhangyanglei The diff property is just a unified diff string that includes other information, if you would like addLine and removeLine values then I suggest you parse the string at the application level.

**Comment by gmessner** [comment]
@zhangyanglei Can we close this issue?
