### ISSUE TITLE
how to  use   api   implement   git clone?

### ISSUE THREAD

**Issue by HQTB123** [gitlab4j/gitlab4j-api#572]

**Comment by gmessner** [comment]
@HQTB123 This library is a wrapper for the GitLab API which does not support clone, so it is not possible.

**Comment by HQTB123** [comment]
If i  want impement  git  clone  , can  I  use  RepositoryFileApi  download   all  the  files

**Comment by gmessner** [comment]
@HQTB123 A ```git clone``` does much more than pull down individual files, it pulls down history all all sorts of other things.  Typically if you want to do a git clone you would simply execute the ```git clone``` CLI command from your application.

Another option is the use JGit which is a Java wrapper for the Git CLI.  Here's an example of cloning with JGit: https://www.codeaffine.com/2015/11/30/jgit-clone-repository/

**Comment by gmessner** [comment]
@HQTB123 I'm going to close this issue, feel free to re-open it if you need additional help.
