### ISSUE TITLE
Missing commit_committer_check and reject_unsigned_commits from PushRules

### ISSUE THREAD

**Issue by GJKrupa** [gitlab4j/gitlab4j-api#574]
The two Gitlab EE push rule restrictions commit_committer_check and reject_unsigned_commits, supported by the GitLab API are not present in the PushRules model object.

I've raised a pull request to add these attributes (I've tested on our Gitlab EE installation).

**Comment by gmessner** [comment]
@GJKrupa First off thank you for your contribution.

GitLab regularly adds fields to the responses. In the future if you find some fields that are not present and you are going to create a PR to add them there is no need to raise an issue, just submit the PR.

**Comment by gmessner** [comment]
@GJKrupa When you have time please verify this in release 4.14.30.

**Comment by GJKrupa** [comment]
Looks good to me with 4.14.30. Thanks very much.
