### ISSUE TITLE
This method is only available to GitLab Starter, Bronze, or higher.

### ISSUE THREAD

**Issue by agreewangshuai** [gitlab4j/gitlab4j-api#576]
这个对应是的gitlab哪个版本？我现在用的是gitlab-ce:12.8.1-ce.0的版本

**Comment by gmessner** [comment]
GitLab Starter, Bronze, and higher are paid licensed versions of GitLab-EE, which includes some functionality not provided by GitLab-CE.

Here is a page that describes this: https://about.gitlab.com/handbook/marketing/product-marketing/tiers/

**Comment by gmessner** [comment]
@agreewangshuai I believe your question has been answered so am closing this issue.
