### ISSUE TITLE
Implement API call to get Blame Data

### ISSUE THREAD

**Issue by ccaspanello** [gitlab4j/gitlab4j-api#577]
Your API is very useful and covers most things I need.  It would be great if you can also implement a method in the RepoistoryFileApi to fetch the blame data.  Currently I have to work around this by making my own HTTP call.  The URL template I'm using looks like this:

String BLAME_URL_TEMPLATE = "%s/api/v4/projects/%s/repository/files/%s/blame?ref=%s";

Hope this helps.

**Comment by gmessner** [comment]
@ccaspanello We've added ```getBlame()``` methods to ```RepositoryFileApi```  This will be included in the next release scheduled for 5/23/2020.  Will let you know when it is available.

**Comment by ccaspanello** [comment]
Thanks man, you rock !!!  I was just pulling down the project and getting the test properties stood up to do some TDD.  You saved me some time :)  I'm going to pull down the code right now and try it out.  Thanks again.

**Comment by ccaspanello** [comment]
@gmessner - Just tested it out against the SNAPSHOT build.  Works flawlessly.  Thank you again.

**Comment by ccaspanello** [comment]
@gmessner - Is there a build pipeline page I can follow to see when the new release is published?

**Comment by gmessner** [comment]
@ccaspanello My apologies, for the late response, but I have been hospitalized with a major accident, and am now just out of the hospital.  

The README.md page automatically displays the latest published version.  It will be a few days before I am able to catch up on things, but expect a release by the end of the week.

**Comment by ccaspanello** [comment]
Oh no!  Happy you are out of the hospital.  Sending you good vibes to you for your road to recovery.

**Comment by gmessner** [comment]
@ccaspanello 4.15.0 has been released with this functionality. Please verify and close when you have time.

**Comment by gmessner** [comment]
@ccaspanello Since this was released a week ago I'm closing this issue. If you have any problems with it please let me know.
