### ISSUE TITLE
Is there a way to get members of a project who are part of shared group?

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#578]
In our Jenkins plugin we need to access all members of a repository to verify if it is a trusted member. Using `getAllMembers()` we get members which includes inherited members through ancestor groups but it doesn't return all members. E.g. GitLab provides [share project with groups ](https://repository.prace-ri.eu/git/help/user/project/members/share_project_with_groups.md) but the inherited members of the shared group are not returned. It only returns members of project and inherited from ancestor group. Is there a way to get members of shared group as well?

**Comment by gmessner** [comment]
@baymac I have looked thru the GitLab API documentation and cannot locate an endpoint to do this.  If you can locate a GitLab API endpoint that does this please provide that and we will implement it.

**Comment by baymac** [comment]
Nope, even I cannot find it. I was checking if you could do some magic to
get the shared group members. But it is okay it is something that should be
solved by GitLab.
