### ISSUE TITLE
GitLabApiException: content is missing, content is empty

### ISSUE THREAD

**Issue by varrix** [gitlab4j/gitlab4j-api#580]
I recently began receiving `GitLabApiException: content is missing, content is empty`. Previously had no issues. I tried upgrading to latest `v4.14.30` and had no changes.

- I read a file into memory from fs and feed that as the contents to a `ProjectApi#createSnippet(...)`.
- I ensured I encounter 0 exceptions during this operation.
- I ensure the returned file *as-a-string* actually does contain content `Validate.notBlank(contentStr)`.
- Even went as far as to manually just use an in-line "test contents" as the contents `string`.
- I've confirmed the user has sufficient access to the repository and has the correct access token defined in my application.

No luck so far.

Code:
```
getGitLabApi().getProjectApi().createSnippet(getRepo(), title, title, description, "test contents", Visibility.PRIVATE);
```

StackTrace:
```
[23:00:57 WARN]: org.gitlab4j.api.GitLabApiException: content is missing, content is empty
[23:00:57 WARN]:        at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
[23:00:57 WARN]:        at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
[23:00:57 WARN]:        at org.gitlab4j.api.ProjectApi.createSnippet(ProjectApi.java:2314)
```

Any thoughts? Has anything internally with GitLab or gitlab4j-api changed recently? If you have any ideas on where I'm going wrong, your feedback/advice would be greatly appreciated.

**Comment by varrix** [comment]
Perhaps https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/AbstractApi.java#L623-L641 is the root of my issue?

**Comment by gmessner** [comment]
@varrix  My apologies for the late response, but I have been hospitalized with a major accident, and am now just out of the hospital.

It looks like GitLab has changed the behavior of the API call and expects the payload to be JSON not a form.  I will fix this and include in the 6/27 release.

**Comment by varrix** [comment]
Thanks for getting back to me! Take your time and good luck on the recovery!

**Comment by gmessner** [comment]
@varrix  4.15.0 has been released with this fixed. Please verify and close when you have time.

**Comment by varrix** [comment]
I can test this out tomorrow morning! Will ping if I have any issues, otherwise I'll mark it as closed. Thanks!

**Comment by gmessner** [comment]
@varrix Can we close this issue?

**Comment by gmessner** [comment]
@varrix Since this functionality was released almost 2 weeks ago I am closing this issue. If you have any problems with it please feel free to re-open.
