### ISSUE TITLE
Include 'all' parameter in Commits API

### ISSUE THREAD

**Issue by fdbatista** [gitlab4j/gitlab4j-api#581]
Hello, team.

I am trying to retrieve the whole list of commits for a project in a given time range.
Using the `commitsApi` this is the best I can do:

`commitsApi.getCommits(1234, "master", "2020-01-01", "2020-06-30", 100)`

The problem is that you consider the ref name parameter as mandatory, but the Gitlab API does not.
And I just need all commits from a project, I don't mind which branch they belong to.

So, right now, I need to loop over project branches and fetch all commits for each branch, which means that I will get duplicated results for all commits merged in different branches. This is not nice, and it consumes a lot of time and network traffic.

On the other hand, you don't provide a `CommitFilter` like you do for pipelines.

So, I would like to translate this API query:

https://gitlab.com/api/v4/projects/13083/repository/commits?all=true&per_page=1000&page=1

into something this, using your library (syntax is not strictly valid):

```
var commitFilter = CommitFilter.builder().all(true).perPage(1000).since("2020-01-01").until("2020-06-30").build();
var pager = commitsApi.getCommits(1234, commitFilter);
//or
var list = commitsApi.getCommits(1234, commitFilter);
```

Could this be possible?

**Comment by gmessner** [comment]
@fdbatista There is a method that will do this for you in the ```CommitsApi```:
```
 public Pager<Commit> getCommits(Object projectIdOrPath, String ref, Date since, Date until,
            String path, Boolean all, Boolean withStats, Boolean firstParent, int itemsPerPage)
```
It is not using a builder pattern but it will work, just pass ```null``` as the ```ref``` and set the ```all``` parameter to true```

I will add a method to take a ```CommitFilter``` in the next release which will be tomorrow.

**Comment by fdbatista** [comment]
@gmessner Hello, Greg. Hope you've had a great weekend.
Setting this `all` parameter will save a lot of time for me, because right now I am looping over the branch list to get all commits.
Will apply your suggestion right now.
Thanks for your hard work!

**Comment by fdbatista** [comment]
@gmessner  The method you suggested me works great. Just one more thing:

Gitlab API is supposed to return a max number of 100 results per page, but it looks like the more commits on the project, the more results you can get per page from the commits endpoint.

The `pager` object is always using 100 as pre-defined value for the page size, even when I use 1000 when creating it. I have a repository with 1350 commits, so I can fetch them all in two steps. But the pager is ignoring the page size I specified and it is assuming 100, so if I use `pager.hasNext()` it will still loop 12 more times unnecessarily, so this forces me to use another stop condition for the `while` loop.

Take a look at this screenshot:
![Screenshot from 2020-06-01 08-19-49](https://user-images.githubusercontent.com/11459171/83409083-adf97f80-a3e1-11ea-9906-d84ade27b35f.png)

This is first iteration. As you can see, the pager knows there are 1354 total results, and the first page already contains a thousand commits. But `itemsPerPage` keeps showing 100. That turns 2 iterations into 14.

**Comment by gmessner** [comment]
@fdbatista  My apologies for the late response, but I have been hospitalized with a major accident, and am now just out of the hospital.

My suggestion would be to use:
```
public List<Commit> getCommits(Object projectIdOrPath, String ref, Date since, Date until,
            String path, Boolean all, Boolean withStats, Boolean firstParent)
```
This will return a list of all commits.

If you want to use the Pager you it is recommended to use the default page size and then simply call ```pager.all()``` or ```pager.stream()``` both will return all commits.

**Comment by fdbatista** [comment]
@gmessner Sorry to hear about your accident, hope everything is going better now.
I will try to use `pager.all` or `.stream` for trying to avoid looping.
Thanks!
