### ISSUE TITLE
Do gitlab4j  have any compatibility matrix with GitLab API version?

### ISSUE THREAD

**Issue by hasangi** [gitlab4j/gitlab4j-api#583]
This is regarding GitLab Endpoint: POST /projects/:id/merge_requests/:merge_request_iid/discussions

With  12.10 GitLab Version, there are new parameters required such as  position[line_range][start_line_code] and position[line_range][end_line_code]. 

But when I try to call gitLabApi.getDiscussionsApi().createMergeRequestDiscussion() it will return 400 BadRequest error. So are there any compatibility version matrix with gitlab4j and gitlab APIs?

**Comment by gmessner** [comment]
@hasangi Unfortunately a compatibility matrix is impossible with the GitLab REST API as changes are made to API calls and are rarely documented by GitLab.
