### ISSUE TITLE
speed problem

### ISSUE THREAD

**Issue by zhangyanglei** [gitlab4j/gitlab4j-api#585]
when i use getGitLabApi().getMergeRequestApi().getMergeRequests(filter, pageSize);
i need wait about 30s.
![image](https://user-images.githubusercontent.com/30100164/84881854-0195e980-b0c1-11ea-845f-e85f55a33fa3.png)

but when i use gitlab api direct it is not need so much seconds
![image](https://user-images.githubusercontent.com/30100164/84881940-22f6d580-b0c1-11ea-9ecc-29ad2a7645af.png)

**Comment by gmessner** [comment]
@zhangyanglei Sorry about the delay in responding I'm recovering from major surgery and cannot spend much time at my computer.

Unfortunately, I cannot replicate your speed problem.

**Comment by gmessner** [comment]
@zhangyanglei Can we close this issue?

**Comment by gmessner** [comment]
@zhangyanglei I'm going to close this issue, please feel free to re-open if needed.
