### ISSUE TITLE
Get a single project label with error org.gitlab4j.api.GitLabApiException: 404 Not Found

### ISSUE THREAD

**Issue by siu91** [gitlab4j/gitlab4j-api#591]
API ：Label getProjectLabel(Object projectIdOrPath, Object labelIdOrName)

use projectId and labelName to get a exist get label,but return "org.gitlab4j.api.GitLabApiException: 404 Not Found"

**Comment by gmessner** [comment]
@siu91 The 404 error implies that either ```projectIdOrPath``` or ```labelIdOrName``` is incorrect.  This method is tested by this projects integration tests and works correctly.

**Comment by gmessner** [comment]
@siu91 I'm closing this issue, if you are still having a problem feel free to re-ope it.
