### ISSUE TITLE
Can I get the content of the file by submitting the historical version

### ISSUE THREAD

**Issue by JavaMrYang** [gitlab4j/gitlab4j-api#592]
I want to get the contents of the file by submitting the historical version

**Comment by gmessner** [comment]
@JavaMrYang To fetch the contents of a file by historical version you would use the ```RepositoryFileApi```.  The ```RepositoryFileApi``` provides different ways to do this refer to the Javadocs for more info:
https://javadoc.io/doc/org.gitlab4j/gitlab4j-api/latest/org/gitlab4j/api/RepositoryFileApi.html

**Comment by gmessner** [comment]
@JavaMrYang Please close this issue if your question has been answered.

**Comment by JavaMrYang** [comment]
fixed
