### ISSUE TITLE
How to create multi level directory by gitlab4j CreateFile API

### ISSUE THREAD

**Issue by JavaMrYang** [gitlab4j/gitlab4j-api#593]
![image](https://user-images.githubusercontent.com/30564116/87498982-ba812100-c68b-11ea-9860-a5bb92ed6f57.png)
Why can't the filepath be graded

**Comment by gmessner** [comment]
@JavaMrYang filepath can be multilevel from the root of the project.  For example if ```test-file.txt``` is desired to be in ```dir/subdir``` then filepath would be ```dir/subdir/test-file.txt```

**Comment by JavaMrYang** [comment]
ok,thank you

**Comment by JavaMrYang** [comment]
fix
