### ISSUE TITLE
getApprovedBy() always null

### ISSUE THREAD

**Issue by javydreamercsw** [gitlab4j/gitlab4j-api#599]
I'm getting Merge Requests for a project using MergeRequestApi. Seems always the `getApprovedBy()` field is always null.

Still happens on 4.15.3.

**Comment by gmessner** [comment]
@javydreamercsw What method(s) are you calling?

**Comment by gmessner** [comment]
@javydreamercsw If ```getApprovals()``` is working, please close this issue.

**Comment by javydreamercsw** [comment]
Will check tomorrow.

**Comment by javydreamercsw** [comment]
I keep getting 404 when trying the call

```
gitLabApi.getMergeRequestApi().getApprovals(project.getId(), mr.getId());
```

**Comment by javydreamercsw** [comment]
I was initially retrieving the merge request like this:

```
                     gitLabApi
                      .getMergeRequestApi()
                      .getMergeRequests(
                          new MergeRequestFilter()
                              .withProjectId(project.getId())
                              .withState(MergeRequestState.OPENED)
                              .withWip(false));
```

**Comment by gmessner** [comment]
@javydreamercsw The GitLab REST API does not return approval information when fetching merge requests, approvals are only returned when fetching approvals (see https://docs.gitlab.com/ce/api/merge_request_approvals.html#get-configuration-1)

The reason you are getting a 404 is that you need to pass in the merge request IID not ID, change:
```
gitLabApi.getMergeRequestApi().getApprovals(project.getId(), mr.getId());
```
to:
```
gitLabApi.getMergeRequestApi().getApprovals(project.getId(), mr.getIid());
```

**Comment by javydreamercsw** [comment]
That did the trick. Thanks!
