### ISSUE TITLE
Project api create project improvment

### ISSUE THREAD

**Issue by jflefebvre06** [gitlab4j/gitlab4j-api#601]
Hello,

Could you please add path to the createProject method

**Comment by gmessner** [comment]
@jflefebvre06 Currently you can use the following method in the ```ProjectApi``  to create a project with a path specified in the ```project``` param:
```
public Project createProject(Project project)
```

In the next release I will add the following convenience method:
```
public Project createProject(String name, String path)
```

**Comment by gmessner** [comment]
@jflefebvre06 Release 4.15.4 is now available with the following added to ```ProjectApi```:
```
public Project createProject(String name, String path)
```
Please verify and close this issue when you have time.

**Comment by jflefebvre06** [comment]
Thank you @gmessner
