### ISSUE TITLE
Remote mirror not supported ?

### ISSUE THREAD

**Issue by WestFarmer** [gitlab4j/gitlab4j-api#602]
seems gitlab already support since 12.9:
https://docs.gitlab.com/ee/api/remote_mirrors.html

**Comment by gmessner** [comment]
@WestFarmer We will add support for the Remote Mirrors API in the next release scheduled to be released by 8/10/2020

**Comment by gmessner** [comment]
@WestFarmer Remote mirror support has been added to the ```ProjectApi``` and is available in release 4.15.5

Please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@WestFarmer Since this has been released a week ago I am closing this issue, if you find any problems, please  feel free to re-open.
