### ISSUE TITLE
project filter grouping

### ISSUE THREAD

**Issue by likeaxa** [gitlab4j/gitlab4j-api#603]
now，i need to get some projects which projects is belongs to the groups。
and i find all ProjectApi that not one api to support my demand 。

**Comment by gmessner** [comment]
The methods to get projects that belong to a group are in the ```GroupApi```

**Comment by gmessner** [comment]
@likeaxa If your question has been resolved please close this issue, if it has not, what can I help you with?

**Comment by jabby** [comment]
No answer since 10 months. I close the issue. 

@likeaxa feel free to reopen if needed and explain what is your problem.
