### ISSUE TITLE
When I create a project hook, 'wiki_event=true' doesn't work

### ISSUE THREAD

**Issue by wndus901** [gitlab4j/gitlab4j-api#606]
I use gitlab4j-api's latest version in my app.

Refer to GitLab API (https://docs.gitlab.com/12.10/ee/api/projects.html#add-project-hook),
Payload that activated the wiki page event is "wiki_pave_event"

But your source says "wiki_event".
Maybe that's why i went through this problem.

Please fix my problem. Thanks

**Comment by jabby** [comment]
Fixed with #718
