### ISSUE TITLE
when i use this for 4.12.12 version to org.gitlab4j.api.ProjectApi.getProject has an error 500 

### ISSUE THREAD

**Issue by anjingyong** [gitlab4j/gitlab4j-api#611]
javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error

Caused by: com.alibaba.fastjson.JSONException: parse enum org.gitlab4j.api.models.AccessLevel error, value : 30

**Comment by gmessner** [comment]
This is due to your project using FastJson.  You'll find a solution here:
https://github.com/gitlab4j/gitlab4j-api/issues/266#issuecomment-519255443

**Comment by jabby** [comment]
@anjingyong is this fixed for you? If so please close the issue.

**Comment by jabby** [comment]
No answer from @anjingyong 
I close the issue. Feel free to reopen if needed.
