### ISSUE TITLE
请问如何初始化项目

### ISSUE THREAD

**Issue by guicaiyue** [gitlab4j/gitlab4j-api#644]
想调用api创建项目后，往项目中上传我本地的项目。或者我创建项目时就上传，请问是哪个api。

**Comment by jabby** [comment]
Hello @guicaiyue 
Can you describe your issue in english please? I only know french and english. 

Thanks.

**Comment by jabby** [comment]
No answer since one month. Feel free to reopen with a proper english desciption of your issue.
