### ISSUE TITLE
Question regarding use of `Object`

### ISSUE THREAD

**Issue by aesy** [gitlab4j/gitlab4j-api#647]
I'm currently in the process of researching which GitLab client library to use for a project and glancing at the code of this project has me wondering why does so many methods accept and return `Object`? For example, rather than having:

```
List<AwardEmoji> getIssueAwardEmojis(Object projectIdOrPath, Integer issueIid)
```

the method could be overloaded, only accepting valid types (also removing boxing of non-nullable primitive types):

```
List<AwardEmoji> getIssueAwardEmojis(int projectId, int issueIid)
List<AwardEmoji> getIssueAwardEmojis(String path, int issueIid)
List<AwardEmoji> getIssueAwardEmojis(Project project, int issueIid)
```

Is a pull request for that something you would consider?

**Comment by jabby** [comment]
I don't know why the first maintainer of the project choose this pattern. I'm quite new as maintainer here and unfortunately I can't ask the previous maintainer. See https://github.com/gitlab4j/gitlab4j-api/issues/650#issuecomment-765056365 for more explanation, 

I'm not sure I will considered such enhancement in version 4.x. Maybe in a 5.x. If many users want that enhancement, I will also reconsidered my answer.
