### ISSUE TITLE
Is the project alive or dead?

### ISSUE THREAD

**Issue by uPagge** [gitlab4j/gitlab4j-api#650]
Is the project alive or dead?

**Comment by imsoftware** [comment]
https://github.com/gitlab4j/gitlab4j-api/pulse/monthly ...

**Comment by uPagge** [comment]
And what should this tell me?

Maybe the project is already so good that there is nothing else to do

**Comment by jabby** [comment]
@imsoftware There is activity on this repository but since last september nothing was merged and @gmessner seems to have less time than before to update gitlab4j-api. 

As I know of, Greg is the only commiter on this project. He did not contribute on any public github repository since last september. Hopefully this is only due to some lack of time.
Is anybody knows if Greg need help on this repository?

**Comment by gmessner** [comment]
Hello. This is Karen, Greg's wife. Unfortunately, with sad heart, I have to let you guys know that Greg just past away recently. I am currently trying to figure out all of his things. I know he wanted this project to continue but I'm not sure how to make this happen. Any thoughts?

**Comment by jabby** [comment]
Hello Karen, 

My sincere condolences to you and your family. 

I already contributed few times to this project. It was a real pleasure to contribute to it with your husband. Maybe I can help you to pass the project to a new team. I can do the interim if you want and looking for new committers.
You can reach me by email: gautier [at] jabby-techs.fr

Gautier

**Comment by gmessner** [comment]
Hello Gautier,

 

Thank you for your kind words. 

 

Yes, if you could help that would be great. Please let me know what you need from me.

 

Kind regards,

Karen

**Comment by gmessner** [comment]
Gautier,

Your help would be greatly appreciated. I not sure how to go about this. Can you direct?

Thank you,
Karen

**Comment by jabby** [comment]
Hi Karen. 

Sorry for not answering quickly. I was busy for some days with my family.
I will send you monday an email in order to explain how to move forward on this project. 

Gautier

**Comment by jabby** [comment]
A little update on this project. The project is actually alive. 
As I said previously, I will do the interim here. I already have the right to push commits and manage travis-ci. 

There left one thing, the biggest one. I need to get the right to push a new release of the project. I start to work on this today. 

Stay tuned for further updates.

**Comment by ludakhris** [comment]
Very sorry to hear about your loss @gmessner 
@jabby if you should need help -- feel free to give me a shout.

**Comment by jabby** [comment]
I close this issue as a new release is available now. 
Stay tuned for upcoming versions.

**Comment by hu-tmx** [comment]
Take my honest condolences. Yes, this project IS still alive, and it rocks. Let us all keep up with the great job of maintaining and extending with new features.
