### ISSUE TITLE
Re-support project issues statistics

### ISSUE THREAD

**Issue by OOnogul** [gitlab4j/gitlab4j-api#656]
Project issues statistics was supported by a method (`geProjectIssuesStatistics()`) for #424 
but then with #480 the method was removed either by a mistake or on purpose. (Commit: 203e968ff4033fb9e0e0c2188caa6627758117ee) 

https://docs.gitlab.com/ee/api/issues_statistics.html#get-project-issues-statistics

Thanks.

**Comment by jabby** [comment]
I will investigate why this method is not available anymore. As Greg is passed away, it will take some times to find the reason of the removal.

**Comment by OOnogul** [comment]
I am truly sorry for your loss. I had no idea. Please accept my condolences.

**Comment by filipowm** [comment]
It seems this can be safely restored, as when I restored it locally, it just worked.
