### ISSUE TITLE
Commits paging works incorrectly

### ISSUE THREAD

**Issue by D-CURT** [gitlab4j/gitlab4j-api#658]
Hello. 

I faced an issue with pagination while iterating by commits. 

Gitlab4j API version: **4.15.7**

I'm calling 
**api.getCommitsApi().getCommits(projectName, branchName, since, until, null, ITEMS_SIZE);** 

And a pager (Pager<Commit>) hasNext() enternally returns **true**. 

So, I'm stucking on:
**while (pager.hasNext()) {
    pager.next();
}**

After pager initialization:
currentPage: 0, kaminariNextPage: 2, itemsPerPage: 100, currentItems: 111 (in my case), totalPages: -1, totalItems: -1.

The first page properties:
currentPage: 1, kaminariNextPage: 2, itemsPerPage: 100, currentItems: 111, totalPages: -1, totalItems: -1.

The second page properties:
currentPage: 2, kaminariNextPage: 3, itemsPerPage: 100, currentItems: 0, totalPages: -1, totalItems: -1.

The third page properties:
currentPage: 3, kaminariNextPage: 4, itemsPerPage: 100, currentItems: 0, totalPages: -1, totalItems: -1.
...

![commist pager call](https://user-images.githubusercontent.com/36221315/108212354-d1ff1b80-713e-11eb-89a3-7c9612cbc5c0.png)

![commits page props](https://user-images.githubusercontent.com/36221315/108212386-dcb9b080-713e-11eb-8360-06786c40991e.png)

![commits pager 1st](https://user-images.githubusercontent.com/36221315/108213559-3a9ac800-7140-11eb-8435-de4e4e7871d5.png)

![commits pager 2nd](https://user-images.githubusercontent.com/36221315/108212911-813bf280-713f-11eb-8782-75d1622e1074.png)

Thanks, 
D-CURT.

**Comment by jabby** [comment]
Hello, 
 Since 13.5 the commits API no longer returns "X-Total-Pages" and "X-Total" headers. I suspect your problem comes from this. Can you confirm that your gitlab instance version is 13.5+?

**Comment by D-CURT** [comment]
Hello, jabby! Thanks for the answer! https://gitlab.com/help shows me 13.11.0-pre.
![gitlab_version](https://user-images.githubusercontent.com/36221315/114514037-84d18e80-9c43-11eb-914a-8bac5f91df22.png)

**Comment by jabby** [comment]
So it's related the removal of "X-Total-Pages" and "X-Total" headers. Thanks for your screenshot.

**Comment by LiuTing0729** [comment]
So, how to resolve this problem if my gitlab version is 13.5+. My company updated gitlab version last week, so I can't lower the version.

**Comment by jabby** [comment]
@LiuTing0729 it should be fixed in 2 latest releases of gitlab4j-api (4.17.0 and 4.18.0). See https://github.com/gitlab4j/gitlab4j-api/commit/4e9f7a6c73259628bcbb37fc3bb88c612c8d6e5a 
Can you check and reopen if it does not work properly?
