### ISSUE TITLE
ProjectAPI.createProject does not appear to use any CustomAttributes

### ISSUE THREAD

**Issue by geeklisted** [gitlab4j/gitlab4j-api#660]
The Project model allows one to specify custom attributes, which will supposedly be passed onto the GitLab API to enable POST parameters not available in the API. However, the custom attribute set never appears to be loaded into the form data that is passed along via HTTP.

**Comment by jabby** [comment]
I did not see a reference to custom attributes in the creation API. See https://docs.gitlab.com/ce/api/projects.html#create-project

I think you should first create the project then create all your custom attributes with projectApi#setCustomAttribute(). See 
https://github.com/gitlab4j/gitlab4j-api/blob/master/src/test/java/org/gitlab4j/api/TestProjectCustomAttributes.java for an example.
