### ISSUE TITLE
add support for `projects/{}/pipelines/{}/test_report`

### ISSUE THREAD

**Issue by matey-jack** [gitlab4j/gitlab4j-api#661]
this is a simple API which returns a bunch of status and a big, non-paged list of "test suites".

I'm thinking of implementing this as method on the "Pipeline" class with the main result class like this:

```
class TestReport {
double totalTime; // example: 1447.2229999999806
  long totalCount; // example: 3540
  long successCount; // example: 3508
  long failedCount; // example: 0
  long skippedCount; // example: 32
  long errorCount; // example: 0
  List<TestSuite> testSuites;
}
```
and `class TestSuite` similarly defined.

any feedback or hints on doing this?

**Comment by jabby** [comment]
Duplicate of #636
