### ISSUE TITLE
Support for Merge Request Reviewers

### ISSUE THREAD

**Issue by ludakhris** [gitlab4j/gitlab4j-api#663]
Recent versions of Gitlab have added support for both Merge Request assignees and reviewers (separated out into 2 categories) you can see what the new Merge Request object looks like here: https://docs.gitlab.com/ee/api/merge_requests.html 

GitLab4J already supports assignees via the MergeRequest.GetAssignees() methods, can there be supported added for Reviewers as well? 

Thanks!

**Comment by jabby** [comment]
A PR was already filled and merged. See https://github.com/gitlab4j/gitlab4j-api/pull/655

It will be part of the next release. I'm working on it. I will closed this issue once the release will be available.

**Comment by ludakhris** [comment]
@jabby I realize you may still be getting spun up on the project but is there a timeline yet for 4.16?

**Comment by jabby** [comment]
I plan to remove some issues from 4.16 to a next milestone and release today the 4.16.
