### ISSUE TITLE
is there a api like command "git log"？

### ISSUE THREAD

**Issue by zyiLoong** [gitlab4j/gitlab4j-api#682]
Hi:
is there a api like command "git log"？  I didn't find it
thanks
>  gitlab version: GitLab Community Edition 13.9.4
> gitlab4j version: 4.15.7

**Comment by maltem-za** [comment]
[Commits API](https://docs.gitlab.com/ee/api/commits.html) [2](https://github.com/gitlab4j/gitlab4j-api#commitsapi) [3](https://javadoc.io/doc/org.gitlab4j/gitlab4j-api/latest/org/gitlab4j/api/CommitsApi.html)?

**Comment by jabby** [comment]
Thanks @maltem-za for your answer. I want to add that if your GitLab instance version is 13.5 or upper, there is a bug with the pager. See #658 for more information (and thanks again @maltem-za for pointing me to the right direction with your PRs)

**Comment by maltem-za** [comment]
@jabby You're welcome - I need the Personal Access Token feature myself, and I noticed the failing tests when setting up the project locally. Then I saw that the previous maintainer had suddenly passed away, so I thought I could at least help out a little to make sure this project keeps going 😊 [CATMA](https://github.com/forTEXT/catma) is heavily dependent on it.

I don't want to write too much off-topic stuff in this issue, but your website link seems to be broken and I was hoping to maybe send you a message directly, just to offer some help or support where I can.

**Comment by zyiLoong** [comment]
Thanks @maltem-za @jabby. Commits API show the commits log for branch,  I know this.
But I want to get last commit of some directory， 
for example, I want get `git log main` or `git log test`  not `git log`
![image](https://user-images.githubusercontent.com/39114043/114807487-1aeaed80-9dd9-11eb-9f0b-8edd403cd957.png)

**Comment by jabby** [comment]
@zyiLoong I did not ckeck if it works but can you try something like the code from this integration test? https://github.com/gitlab4j/gitlab4j-api/blob/master/src/test/java/org/gitlab4j/api/TestCommitsApi.java#L180-L197

**Comment by zyiLoong** [comment]
@jabby 
yes, it is what I need, thanks a lot
good luck to you
