### ISSUE TITLE
Does gitlab4j-api allow to commit file without have the repo cloned?

### ISSUE THREAD

**Issue by elect86** [gitlab4j/gitlab4j-api#700]
As titled, I'd like to know if gitlab4j-api offers the possibility to commit multiple files to a gitlab repo without having the repo cloned locally

I couldn't find anything about

**Comment by jabby** [comment]
You can create a new commit through the CommitApi of GitLab. Please check https://github.com/gitlab4j/gitlab4j-api/blob/master/src/test/java/org/gitlab4j/api/TestCommitsApi.java for some examples of how to use CommitAction and CommitApi.

**Comment by jabby** [comment]
No answer from @elect86 
I close the issue. Feel free to reopen if needed.

**Comment by elect86** [comment]
Sorry, I solved in the meanwhile with http4k
