### ISSUE TITLE
how can i do git add, git commit and git push with api?

### ISSUE THREAD

**Issue by AudiVehicle** [gitlab4j/gitlab4j-api#702]
how can i do git add, git commit and git push with api?  much thx

**Comment by jabby** [comment]
Hello @AudiVehicle

As already answered [here](https://github.com/gitlab4j/gitlab4j-api/issues/342#issuecomment-490732679), you can't push through the API. But you can create a commit with a file. Here is an example in our tests : https://github.com/gitlab4j/gitlab4j-api/blob/master/src/test/java/org/gitlab4j/api/TestCommitsApi.java#L249-L285

**Comment by jabby** [comment]
No answer from @AudiVehicle
I close the issue. Feel free to reopen if needed.
