### ISSUE TITLE
Code health proposal: use lombok

### ISSUE THREAD

**Issue by mucst** [gitlab4j/gitlab4j-api#712]
There's quite a lot of setters, getters and with-ers (also toString()) in the model classes. Perhaps lombok could help us reduce all this boilerplate code... What do you think?

**Comment by jabby** [comment]
Thanks for rising this issue. 
Actually in version 4.X.Y of this project I don´t want to introduce lombok. See @gmessner answer some times ago https://github.com/gitlab4j/gitlab4j-api/issues/271#issuecomment-572858974

I will let this open for a next major release.

**Comment by jmini** [comment]
See https://github.com/gitlab4j/gitlab4j-api/issues/494
