### ISSUE TITLE
EpicApi.getEpicIssues() returns models.Epic not models.EpicIssue

### ISSUE THREAD

**Issue by Zojii** [gitlab4j/gitlab4j-api#729]
Shouldn't the below code returning List<EpicIssue> ?  Happy to contribute if the below isn't the intended behavior.  There are several other epicIssue methods return epics.   

[List<Epic> getEpicIssues](https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/EpicsApi.java#:~:text=public%20List%3CEpic%3E%20getEpicIssues(Object%20groupIdOrPath%2C%20Integer%20epicIid%2C%20int%20page%2C%20int%20perPage)%20throws%20GitLabApiException%20%7B)   

[public Pager<Epic> getEpicIssues](https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/EpicsApi.java#:~:text=public%20Pager%3CEpic%3E%20getEpicIssues(Object%20groupIdOrPath%2C%20Integer%20epicIid%2C%20int%20itemsPerPage)%20throws%20GitLabApiException).  

[public Stream<Epic> getEpicIssuesStr](https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/EpicsApi.java#:~:text=public%20Stream%3CEpic%3E%20getEpicIssuesStream(Object%20groupIdOrPath%2C%20Integer%20epicIid)%20throws%20GitLabApiException).  

```java
/**
     * Gets all issues that are assigned to an epic and the authenticated user has access to
     * using the specified page and per page setting.
     *
     * <pre><code>GitLab Endpoint: GET /groups/:id/epics/:epic_iid/issues</code></pre>
     *
     * @param groupIdOrPath the group ID, path of the group, or a Group instance holding the group ID or path
     * @param epicIid the IID of the epic to get issues for
     * @param page the page to get
     * @param perPage the number of issues per page
     * @return a list of all epic issues belonging to the specified epic in the specified range
     * @throws GitLabApiException if any exception occurs
     */
    public List<Epic> getEpicIssues(Object groupIdOrPath, Integer epicIid, int page, int perPage) throws GitLabApiException {
        Response response = get(Response.Status.OK, getPageQueryParams(page, perPage), "groups", getGroupIdOrPath(groupIdOrPath), "epics", epicIid, "issues");
        return (response.readEntity(new GenericType<List<Epic>>() { }));
    }
    ```

**Comment by jmini** [comment]
I totally agree with this issue.

---

This is a little bit the same story as what I have described here: https://github.com/gitlab4j/gitlab4j-api/pull/964#issue-1681125362

We need an `AbstractIssue` type containing most of the current `Issue` attributes.

* `Issue` would extends `AbstractIssue`
     * Just `subscribed` would stay on the concrete `Issue` type.
* The new class `EpicIssue` would also extends `AbstractIssue` with following attribues:
     * `epic_issue_id` Long
     * `relative_position` Integer

---

I guess `getEpicIssues(..)` is not working for anybody, so for me it would be OK to change that now on `5.x.x`
