### ISSUE TITLE
how to create a subgroup in group?

### ISSUE THREAD

**Issue by xiedeacc** [gitlab4j/gitlab4j-api#754]
at title

**Comment by xiedeacc** [comment]
use createGroup will said cannot path cannot contain '/'. this project is designed very badly, so hard to use,  my god!!!!!!

**Comment by jabby** [comment]
Duplicate of #753

**Comment by jabby** [comment]
Sorry for closing this issue. I read this to quickly.

**Comment by xiedeacc** [comment]
use   groupParams.withName(group_names[i]);
                    groupParams.withPath(group_names[i]);
                    groupParams.withParentId(group.getId());
                    group = gitLabApi.getGroupApi().createGroup(groupParams);
