### ISSUE TITLE
Merge check functions are not working

### ISSUE THREAD

**Issue by gowtk** [gitlab4j/gitlab4j-api#785]
The below two methods are not working. Its not enablng / disabling the Merge Check 

Verified with latest version also : 4.19.0

**Pipelines must succeed**
gitLabApi.getProjectApi().getProject(groupName,projectName).setOnlyAllowMergeIfPipelineSucceeds(false);

**All discussions must be resolved**
gitLabApi.getProjectApi().getProject(groupName,projectName).setOnlyAllowMergeIfAllDiscussionsAreResolved(false);

**Comment by jabby** [comment]
Which version of GitLab did you use?

**Comment by gowtk** [comment]
4.19.0

I found a solution and this works. But not sure this will unset and other values. 
            Project project = new Project();
	    project.setId(1);
	    project.setOnlyAllowMergeIfAllDiscussionsAreResolved(true);
	    project.setOnlyAllowMergeIfPipelineSucceeds(true);
	    gitLabApi.getProjectApi().updateProject(project);

**Comment by jabby** [comment]
Thanks for the version of gitlab4j-api
What about GitLab instance. Is it GitLab.com? GitLab 12.x, 13.x or 14.x?

**Comment by HaoZinger** [comment]
@jabby  
I'm use GitLab-ce  13.11.0
i met same problem when i update this config in some project.otherwise some other project were success. i haven't found difference between these projects.

**Comment by HaoZinger** [comment]
> @jabby I'm use GitLab-ce 13.11.0 i met same problem when i update this config in some project.otherwise some other project were success. i haven't found difference between these projects.

i found same issue [here(issues/628)](https://github.com/gitlab4j/gitlab4j-api/issues/628), don't find a way to fix this in gitlab4j-api. may be i must write http request to work out?

**Comment by gowtk** [comment]
I found a solution and this works. 
Project project = new Project();
project.setId(1);
project.setOnlyAllowMergeIfAllDiscussionsAreResolved(true);
project.setOnlyAllowMergeIfPipelineSucceeds(true);
gitLabApi.getProjectApi().updateProject(project);
