### ISSUE TITLE
How do I get the project for my group.

### ISSUE THREAD

**Issue by peterpsihogios** [gitlab4j/gitlab4j-api#787]
Wondering if someone can give me a hand. Trying out the API to get some stats on our companies commits. The structure we have in git is a Group < Sub Group > Projects > Branches > Commits

using the api to do a basic search down the tree.

Group goGroup = gitLabApi.getGroupApi().getGroup(147);
for (Group custGroup : GitLabUtils.getGitLabApi().getGroupApi().getSubGroups(147)) {
   read projects     <<------ stuck here right now because i cant find a way to get the project for the subgroup.
       read branches
            read commits
}

Its possible the goGroup AND custGroup both have Projects assigned. When I inspect the returned goGroup and custGroup object results, the projects tag is empty in both scenarios yet in Git they definitely have projects assigned.

I tried a few things and short of reading all projects and doing my own filtering, could not find a way to read the projects for a specific Group.

any ideas as to the best way to use the API's to do this?

**Comment by jabby** [comment]
If I understand correctly you are looking for this method. https://github.com/gitlab4j/gitlab4j-api/blob/18d69022f24099e10931dfe4c73a1dcf0154e765/src/main/java/org/gitlab4j/api/GroupApi.java#L366-L380

**Comment by peterpsihogios** [comment]
Thanks. That did the trick. Now I have the commits for my the group, project and branch. From the commit is there a way to get the files that were changed as part of that commit? thanks for the help in trying to find my way through the API.
