### ISSUE TITLE
Proposal to update all IDs to Long 

### ISSUE THREAD

**Issue by iroussos** [gitlab4j/gitlab4j-api#810]
Hi, I am a member of the Database Group at GitLab.

I am creating this issue in response to a few other issues I can see already created (https://github.com/gitlab4j/gitlab4j-api/issues/805, https://github.com/gitlab4j/gitlab4j-api/issues/809)

It seems that there are GitLab projects with more than 2.15 Billion builds, which means that you have to switch to using a Long integer for those IDs. 

In general, most IDs in GitLab are using 8-byte integers, with a few old tables (pre rails 5.1) that were using 4-byte integers for their PKs. Those are also being transitioned to use 8-byte integers, so you can safely assume that in the long run all the IDs will be 8-byte integers. (You can find more details in a recent [epic](https://gitlab.com/groups/gitlab-org/-/epics/4785) where we documented our efforts to address the tables at most risk to overflow)

If you agree, I would propose that you switch all the IDs in `gitlab4j` to `Long` from `Integer`. Thank you!

**Comment by jabby** [comment]
@iroussos I will update all the IDS to `Long` next week.

**Comment by iroussos** [comment]
Thank you @jabby!

**Comment by jabby** [comment]
I'm not sure which version number I should use for this. Actually, gitlab4j-api does not follow `semver` but this is a kind of bigbang. Should I use 5.x version for this ? If so, should I also clean some of the API like finally removing V3 support?

@iroussos do you have a suggestion?
