### ISSUE TITLE
New release with updated jersey versions

### ISSUE THREAD

**Issue by jasonk619** [gitlab4j/gitlab4j-api#825]
Is it possible to get a new release out to maven with the updated jersey versions? Latest gitlab4j version **4.19.0** is using jersey version **2.30.1**  which has some vulnerabilities

**Comment by jabby** [comment]
Next release will rely on jersey `2.34`. See current pom.xml on master branch. I will check if I can upgrade to `2.35` before releasing.

BTW, next release will happen in few hours.

**Comment by jasonk619** [comment]
Thank you jabby! I will wait for the new release!
