### ISSUE TITLE
PipelineId still int instead of long

### ISSUE THREAD

**Issue by Jasper-ui** [gitlab4j/gitlab4j-api#829]
![image](https://user-images.githubusercontent.com/68504707/158972492-505b78d8-6660-4ba9-9eb7-fee8ae084e58.png)

**Comment by jabby** [comment]
Thanks for your report. Seems I miss some methods update. Should be available soon in a 5.0.1

**Comment by Jasper-ui** [comment]
@jabby No worries! Also, can we modify the projectIdOrPath object to also accept int? It's looking for long at the moment and that's annoying to deserialize

**Comment by jabby** [comment]
So you want to accept the following parameters: 
- Long (it replace Integer in 5.0 version)
- String
- Project
- Integer 

Can you explain what is annoying about `Long`? In fact I replaced Integer to Long in 5.0.0 version to comply with the fact that all IDs are now `Long`. I can add the Integer case but I want to understand your problem.

**Comment by jabby** [comment]
For the record I also need to fix `public NotificationSettings updateProjectNotificationSettings(int projectId, NotificationSettings settings) throws GitLabApiException`

**Comment by jabby** [comment]
@Jasper-ui release 5.0.1 is available on maven central.
