### ISSUE TITLE
Tags in Project API are deprecated

### ISSUE THREAD

**Issue by DaspawnW** [gitlab4j/gitlab4j-api#858]
In a project I'm currently working on I have to create gitlab projects via the gitlab4j-api. Thanks a lot for the great work!!
The projects we create get topics to be better able to filter based on them. It seems that gitlab4j-api so far only supports the deprecated tags and not the new recommended topics. https://docs.gitlab.com/ee/api/projects.html#create-project

Is there any plan to implement it?

Thank you in advance,
Björn

**Comment by NadeoWolf** [comment]
Hi,

Added the missing TopicsApi. 

https://github.com/gitlab4j/gitlab4j-api/pull/1012

Best Regards, 
Nadeo
