### ISSUE TITLE
Missing 'state' attribute for Epic

### ISSUE THREAD

**Issue by mianfca** [gitlab4j/gitlab4j-api#887]
Epic class is missing the 'state' or 'EpicState' attribute, which is provided by the Gitlab API.

<html>
<body>

state | string | ... | Search epics against their state, possible filters: opened, closed and all, default: all
-- | -- | -- | --

</body>
</html>

see https://docs.gitlab.com/ee/api/epics.html

**Comment by jmini** [comment]
Thank you for the issue.

Feel free to create a Pull Request for that.
