### ISSUE TITLE
When running gitlab API after upgrade to spring boot 3.0.2 (with the latest dependencies), gitlab initialization fails

### ISSUE THREAD

**Issue by serleonsolo2** [gitlab4j/gitlab4j-api#918]
The error is as follows:

**Location:
    org/gitlab4j/api/GitLabApiClient.createApiClient()Ljavax/ws/rs/client/Client; @18: invokevirtual
  Reason:
    Type 'org/glassfish/jersey/client/JerseyClientBuilder' (current frame, stack[0]) is not assignable to 'javax/ws/rs/client/ClientBuilder'**

Could you plz help at least with workarround

I am using the latest version:
```
<groupId>org.gitlab4j</groupId>
artifactId>gitlab4j-api</artifactId>
version>5.0.1</version>
```

**Comment by serleonsolo2** [comment]
see, that you alreasy working on migrate to jakarta and spring boot 3

**Comment by jmini** [comment]
See the version `6.x.x` where we moved to the `jakarta.*` namespace (to have a compatibility with SpringBoot 3 or Quarkus 3).

See https://github.com/gitlab4j/gitlab4j-api/pull/947
