### ISSUE TITLE
cancel merge request http method use post not put

### ISSUE THREAD

**Issue by fighter2011** [gitlab4j/gitlab4j-api#931]
`POST /projects/:id/merge_requests/:merge_request_iid/cancel_merge_when_pipeline_succeeds`

**Comment by jmini** [comment]
This is the documentation:
https://docs.gitlab.com/ee/api/merge_requests.html#cancel-merge-when-pipeline-succeeds

This is our code:
https://github.com/gitlab4j/gitlab4j-api/blob/ea9042ee96fcd9807fecfeabe27f0a85286709c8/src/main/java/org/gitlab4j/api/MergeRequestApi.java#L797-L820
