### ISSUE TITLE
Get Merge Requests By GroupId?

### ISSUE THREAD

**Issue by Erkanerkisi** [gitlab4j/gitlab4j-api#932]
Hey,

I couldn't find any sign of "getting all merge requests by groupId".It seems we can implement it, right? Or Is there any specific reason not doing it?

https://docs.gitlab.com/ee/api/merge_requests.html#list-group-merge-requests

Thanks.

**Comment by jmini** [comment]
I think this would be a good addition. Feel free to submit a pull request

**Comment by Erkanerkisi** [comment]
okey, you can assign me. Thanks.
