### ISSUE TITLE
Pipeline is missing iid

### ISSUE THREAD

**Issue by SirUppyPancakes** [gitlab4j/gitlab4j-api#966]
The Pipelines API also returns an internal ID (`iid`) as seen [here](https://docs.gitlab.com/ee/api/pipelines.html), but the `Pipeline` class in this library is missing the field. Would be great to have this added!

Also, as a new user of this library, I was surprised that the raw JSON wasn't exposed on the model somehow, leaving me with no other options besides opening an issue for a fix or dropping down and doing the request entirely myself. Have you considered making the raw JSON available on models?

**Comment by jmini** [comment]
I think your request is solved with https://github.com/gitlab4j/gitlab4j-api/pull/959

---

About keeping the JSON, this is an interesting idea, but not quite typical when having java models and Jackson.

What I sometimes see is a pattern like this to be able to collect unknown properties:

```java
@JsonIgnore
private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

@JsonAnyGetter
public Map<String, Object> getAdditionalProperties() {
   return this.additionalProperties;
}

@JsonAnySetter
public void setAdditionalProperty(String name, Object value) {
    this.additionalProperties.put(name, value);
}
```

But this makes your code breaking as soon as the attribute is added for real to the model.

Personally I would prefer to have complete models in Java.

**Comment by SirUppyPancakes** [comment]
Ah yes thanks I didn't see that MR! I'll close this issue.

---

Hmm yes you raise some good points there. Also, I appreciate that the API methods and models weren't made private or final, so I still had an option to fix it locally without waiting for an update.
For anyone else who comes across this in the future, here's what I did while waiting for the update:
```java
public class PipelineEx extends Pipeline {
    // add whatever missing fields I needed here
}
public class PipelineApiEx extends PipelineApi {
    // implement my own method returning or taking PipelineEx
    // you can look at the source code inside PipelineApi to see how to do it and there are even protected helper methods available from here
}
```
