### ISSUE TITLE
unable to find path for getArchive api

### ISSUE THREAD

**Issue by ramarro123** [gitlab4j/gitlab4j-api#982]
for api

https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

i can't see how to specify the path parameter (that should fetch just part of repository)

can you give me an hint please? :)

sing 6.0.0 rc1

**Comment by jmini** [comment]
I think you are right, the `path` parameter is missing from the `getRepositoryArchive()` methods in `RepositoryApi`.

According to the "Version history" on the linked documentation, path was added with `14.4`.

So a PR is welcomed to add it to this project.

**Comment by DoubleDPro** [comment]
In work!

**Comment by DoubleDPro** [comment]
@jmini I made a PR. Can you check it?
