### ISSUE TITLE
Approval rule for spedific branch

### ISSUE THREAD

**Issue by dmytro-biblyi-fairo** [gitlab4j/gitlab4j-api#984]
Currently it's impossible to add [protected_branch_ids ](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule) to Approval rules if I want to create rule for specific branch. 
please add withProtectedBranchId to ApprovalRuleParams

**Comment by jmini** [comment]
I agree, this would be a good contribution. Can you file a PR?
