### ISSUE TITLE
fabric8io docker-maven-plugin version does not support Mac M1 chip

### ISSUE THREAD

**Issue by harsh-ps-2003** [gitlab4j/gitlab4j-api#985]
When trying to do `mvn clean install` to obtain a snapshot of gitalb4j-api i encountered this 
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.30.0:start (start) on project gitlab4j-api: Execution start of goal io.fabric8:docker-maven-plugin:0.30.0:start failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.30.0:start: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
```

On digging deeper on this issue i found [this](https://github.com/fabric8io/docker-maven-plugin/issues/1257) which conveys that the current version of docker-maven-plugin i.e 0.30.0 does not support M1 chips. 
Kindly update the docker-maven-plugin's version to make it compatible wiht Apple M1 chips.

Thank you for this awesome library!
Warm Regards

**Comment by harsh-ps-2003** [comment]
I tried solving this issue by simply changing the docker-maven-plugins version but i was not able to get the integration tests running! @gmessner

**Comment by jmini** [comment]
Those integration tests are tricky and we plan to do something different in the future:
https://github.com/gitlab4j/gitlab4j-api/issues/925

Until this is solved, I am sure we could update the `docker-maven-plugin` if this helps you.

Can you share what you did until now and tell what is blocking?

**Comment by harsh-ps-2003** [comment]
Thanks for the fast response @gmessner much appreciated!
`Until this is solved, I am sure we could update the docker-maven-plugin if this helps you.` - okay! so I will make a PR for this simply changing the version of the plugin.

When simply changing the `docker-maven-plugin` version to a more latest version the integration tests failed but unit tests were working perfectly fine. On running the integration tests I got these : 
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.782 s <<< FAILURE! - in org.gitlab4j.api.TestAvatarUpload
[ERROR] org.gitlab4j.api.TestAvatarUpload  Time elapsed: 2.782 s  <<< ERROR!
org.gitlab4j.api.GitLabApiException: invalid_grant
```
which I think are happening because the user is not being configured my side properly for some reason!
Unfortunately there is not much documentation available related to setting up the integration tests :(
