### ISSUE TITLE
Missing `closed_at` and `references` properties from `Epic` model

### ISSUE THREAD

**Issue by hsebouai** [gitlab4j/gitlab4j-api#988]

**Comment by hsebouai** [comment]
Here is a sample of the response based on Gitlab [documentation](https://docs.gitlab.com/ee/api/epics.html#single-epic):

```{
  "id": 30,
  "iid": 5,
  ...
  "references": {
    "short": "&5",
    "relative": "&5",
    "full": "test&5"
  },
  ...
  "closed_at": "2018-08-18T12:22:05.239Z",
  ...
}
```

**Comment by jmini** [comment]
I worked on epics on this PR https://github.com/gitlab4j/gitlab4j-api/pull/961

Can you check one of the 2 versions released this morning (`6.0.0-rc.2` and `5.3.0`) and give me feedback?

* `5.3.0` requires Java 8 as minimal version and using a Jersey version using `javax.*` packages (for servlet, jaxrs and similar).
* `6.0.0-rc.2` requires Java 11 as minimal version and using a Jersey version using `jakarta.*` packages (for servlet, jaxrs and similar).

**Comment by jmini** [comment]
I doubled check my PR and I think you will have what you need.

Feel free to re-open and continue the discussion if this is not the case.

**Comment by hsebouai** [comment]
Indeed in the latest version 5.3.0, the `closedAt` is present but the `references` object is still missing and I think it's duplicate of #871
